package com.blockchain.commune.model;

import java.util.Date;

public class CommentReplay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_replay.replay_id
     *
     * @mbg.generated
     */
    private String replayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_replay.comment_id
     *
     * @mbg.generated
     */
    private String commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_replay.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_replay.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_replay.replay_context
     *
     * @mbg.generated
     */
    private String replayContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_replay.re_user_id
     *
     * @mbg.generated
     */
    private String reUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_replay.re_name
     *
     * @mbg.generated
     */
    private String reName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_replay.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_replay.user_icon
     *
     * @mbg.generated
     */
    private String userIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_replay.replay_id
     *
     * @return the value of comment_replay.replay_id
     *
     * @mbg.generated
     */
    public String getReplayId() {
        return replayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_replay.replay_id
     *
     * @param replayId the value for comment_replay.replay_id
     *
     * @mbg.generated
     */
    public void setReplayId(String replayId) {
        this.replayId = replayId == null ? null : replayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_replay.comment_id
     *
     * @return the value of comment_replay.comment_id
     *
     * @mbg.generated
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_replay.comment_id
     *
     * @param commentId the value for comment_replay.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(String commentId) {
        this.commentId = commentId == null ? null : commentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_replay.user_id
     *
     * @return the value of comment_replay.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_replay.user_id
     *
     * @param userId the value for comment_replay.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_replay.name
     *
     * @return the value of comment_replay.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_replay.name
     *
     * @param name the value for comment_replay.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_replay.replay_context
     *
     * @return the value of comment_replay.replay_context
     *
     * @mbg.generated
     */
    public String getReplayContext() {
        return replayContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_replay.replay_context
     *
     * @param replayContext the value for comment_replay.replay_context
     *
     * @mbg.generated
     */
    public void setReplayContext(String replayContext) {
        this.replayContext = replayContext == null ? null : replayContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_replay.re_user_id
     *
     * @return the value of comment_replay.re_user_id
     *
     * @mbg.generated
     */
    public String getReUserId() {
        return reUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_replay.re_user_id
     *
     * @param reUserId the value for comment_replay.re_user_id
     *
     * @mbg.generated
     */
    public void setReUserId(String reUserId) {
        this.reUserId = reUserId == null ? null : reUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_replay.re_name
     *
     * @return the value of comment_replay.re_name
     *
     * @mbg.generated
     */
    public String getReName() {
        return reName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_replay.re_name
     *
     * @param reName the value for comment_replay.re_name
     *
     * @mbg.generated
     */
    public void setReName(String reName) {
        this.reName = reName == null ? null : reName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_replay.create_time
     *
     * @return the value of comment_replay.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_replay.create_time
     *
     * @param createTime the value for comment_replay.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_replay.user_icon
     *
     * @return the value of comment_replay.user_icon
     *
     * @mbg.generated
     */
    public String getUserIcon() {
        return userIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_replay.user_icon
     *
     * @param userIcon the value for comment_replay.user_icon
     *
     * @mbg.generated
     */
    public void setUserIcon(String userIcon) {
        this.userIcon = userIcon == null ? null : userIcon.trim();
    }
}