package com.blockchain.commune.model;

import java.util.Date;

public class CommentGreat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_great.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_great.comment_id
     *
     * @mbg.generated
     */
    private String commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_great.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_great.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_great.id
     *
     * @return the value of comment_great.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_great.id
     *
     * @param id the value for comment_great.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_great.comment_id
     *
     * @return the value of comment_great.comment_id
     *
     * @mbg.generated
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_great.comment_id
     *
     * @param commentId the value for comment_great.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(String commentId) {
        this.commentId = commentId == null ? null : commentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_great.user_id
     *
     * @return the value of comment_great.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_great.user_id
     *
     * @param userId the value for comment_great.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_great.create_time
     *
     * @return the value of comment_great.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_great.create_time
     *
     * @param createTime the value for comment_great.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}