package com.blockchain.commune.model;

public class DirAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dir_auth.dir_name
     *
     * @mbg.generated
     */
    private String dirName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dir_auth.role_level
     *
     * @mbg.generated
     */
    private Integer roleLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dir_auth.dir_name
     *
     * @return the value of dir_auth.dir_name
     *
     * @mbg.generated
     */
    public String getDirName() {
        return dirName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dir_auth.dir_name
     *
     * @param dirName the value for dir_auth.dir_name
     *
     * @mbg.generated
     */
    public void setDirName(String dirName) {
        this.dirName = dirName == null ? null : dirName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dir_auth.role_level
     *
     * @return the value of dir_auth.role_level
     *
     * @mbg.generated
     */
    public Integer getRoleLevel() {
        return roleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dir_auth.role_level
     *
     * @param roleLevel the value for dir_auth.role_level
     *
     * @mbg.generated
     */
    public void setRoleLevel(Integer roleLevel) {
        this.roleLevel = roleLevel;
    }
}