package com.blockchain.commune.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;
import java.util.Date;
@JsonIgnoreProperties(ignoreUnknown = true)
public class MarketCapSpider {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cap.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cap.symbol
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cap.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cap.price_usd
     *
     * @mbg.generated
     */
    @JsonProperty("price_usd")
    private BigDecimal priceUsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cap.market_cap_display_cny
     *
     * @mbg.generated
     */
    @JsonProperty("market_cap_display_cny")
    private BigDecimal marketCapDisplayCny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cap.volume_24h
     *
     * @mbg.generated
     */
    @JsonProperty("volume_24h")
    private BigDecimal volume24h;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cap.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cap.alias
     *
     * @mbg.generated
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cap.rank
     *
     * @mbg.generated
     */
    private Integer rank;

    private String batch;

    public String getBatch() {
        return batch;
    }

    public void setBatch(String batch) {
        this.batch = batch;
    }

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cap.percent_change_display
     *
     * @mbg.generated
     */
    @JsonProperty("percent_change_display")
    private BigDecimal percentChangeDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cap.volume_24h_usd
     *
     * @mbg.generated
     */
    @JsonProperty("volume_24h_usd")
    private BigDecimal volume24hUsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_cap.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_cap.id
     *
     * @return the value of market_cap.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_cap.id
     *
     * @param id the value for market_cap.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_cap.symbol
     *
     * @return the value of market_cap.symbol
     *
     * @mbg.generated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_cap.symbol
     *
     * @param symbol the value for market_cap.symbol
     *
     * @mbg.generated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_cap.price
     *
     * @return the value of market_cap.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_cap.price
     *
     * @param price the value for market_cap.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_cap.price_usd
     *
     * @return the value of market_cap.price_usd
     *
     * @mbg.generated
     */
    public BigDecimal getPriceUsd() {
        return priceUsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_cap.price_usd
     *
     * @param priceUsd the value for market_cap.price_usd
     *
     * @mbg.generated
     */
    public void setPriceUsd(BigDecimal priceUsd) {
        this.priceUsd = priceUsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_cap.market_cap_display_cny
     *
     * @return the value of market_cap.market_cap_display_cny
     *
     * @mbg.generated
     */
    public BigDecimal getMarketCapDisplayCny() {
        return marketCapDisplayCny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_cap.market_cap_display_cny
     *
     * @param marketCapDisplayCny the value for market_cap.market_cap_display_cny
     *
     * @mbg.generated
     */
    public void setMarketCapDisplayCny(BigDecimal marketCapDisplayCny) {
        this.marketCapDisplayCny = marketCapDisplayCny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_cap.volume_24h
     *
     * @return the value of market_cap.volume_24h
     *
     * @mbg.generated
     */
    public BigDecimal getVolume24h() {
        return volume24h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_cap.volume_24h
     *
     * @param volume24h the value for market_cap.volume_24h
     *
     * @mbg.generated
     */
    public void setVolume24h(BigDecimal volume24h) {
        this.volume24h = volume24h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_cap.logo
     *
     * @return the value of market_cap.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_cap.logo
     *
     * @param logo the value for market_cap.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_cap.alias
     *
     * @return the value of market_cap.alias
     *
     * @mbg.generated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_cap.alias
     *
     * @param alias the value for market_cap.alias
     *
     * @mbg.generated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_cap.rank
     *
     * @return the value of market_cap.rank
     *
     * @mbg.generated
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_cap.rank
     *
     * @param rank the value for market_cap.rank
     *
     * @mbg.generated
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_cap.percent_change_display
     *
     * @return the value of market_cap.percent_change_display
     *
     * @mbg.generated
     */
    public BigDecimal getPercentChangeDisplay() {
        return percentChangeDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_cap.percent_change_display
     *
     * @param percentChangeDisplay the value for market_cap.percent_change_display
     *
     * @mbg.generated
     */
    public void setPercentChangeDisplay(BigDecimal percentChangeDisplay) {
        this.percentChangeDisplay = percentChangeDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_cap.volume_24h_usd
     *
     * @return the value of market_cap.volume_24h_usd
     *
     * @mbg.generated
     */
    public BigDecimal getVolume24hUsd() {
        return volume24hUsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_cap.volume_24h_usd
     *
     * @param volume24hUsd the value for market_cap.volume_24h_usd
     *
     * @mbg.generated
     */
    public void setVolume24hUsd(BigDecimal volume24hUsd) {
        this.volume24hUsd = volume24hUsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_cap.create_time
     *
     * @return the value of market_cap.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_cap.create_time
     *
     * @param createTime the value for market_cap.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}