package com.blockchain.commune.model;

import com.blockchain.commune.utils.IdUtil;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;
import java.util.Date;
@JsonIgnoreProperties(ignoreUnknown = true)
public class MarketTradeOnSpider {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_trade_on.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_trade_on.symbol
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_trade_on.market_id
     *
     * @mbg.generated
     */
    @JsonProperty("market_id")
    private String marketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_trade_on.market_name
     *
     * @mbg.generated
     */
    @JsonProperty("market_name")
    private String marketName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_trade_on.pair
     *
     * @mbg.generated
     */
    private String pair;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_trade_on.price_display
     *
     * @mbg.generated
     */
    @JsonProperty("price_display")
    private String priceDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_trade_on.hr_price_display
     *
     * @mbg.generated
     */
    @JsonProperty("hr_price_display")
    private String hrPriceDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_trade_on.percent_change_display
     *
     * @mbg.generated
     */
    @JsonProperty("percent_change_display")
    private BigDecimal percentChangeDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_trade_on.market_alias
     *
     * @mbg.generated
     */
    @JsonProperty("market_alias")
    private String marketAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_trade_on.create_time
     *
     * @mbg.generated
     */
    private Date createTime;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_trade_on.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_trade_on.price
     *
     * @mbg.generated
     */
    private BigDecimal price;
    private String sortId;

    public String getSortId() {
        return sortId;
    }

    public void setSortId(String sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_trade_on.id
     *
     * @return the value of market_trade_on.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_trade_on.id
     *
     * @param id the value for market_trade_on.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.setSortId(IdUtil.getId());
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_trade_on.symbol
     *
     * @return the value of market_trade_on.symbol
     *
     * @mbg.generated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_trade_on.symbol
     *
     * @param symbol the value for market_trade_on.symbol
     *
     * @mbg.generated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_trade_on.market_id
     *
     * @return the value of market_trade_on.market_id
     *
     * @mbg.generated
     */
    public String getMarketId() {
        return marketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_trade_on.market_id
     *
     * @param marketId the value for market_trade_on.market_id
     *
     * @mbg.generated
     */
    public void setMarketId(String marketId) {
        this.marketId = marketId == null ? null : marketId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_trade_on.market_name
     *
     * @return the value of market_trade_on.market_name
     *
     * @mbg.generated
     */
    public String getMarketName() {
        return marketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_trade_on.market_name
     *
     * @param marketName the value for market_trade_on.market_name
     *
     * @mbg.generated
     */
    public void setMarketName(String marketName) {
        this.marketName = marketName == null ? null : marketName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_trade_on.pair
     *
     * @return the value of market_trade_on.pair
     *
     * @mbg.generated
     */
    public String getPair() {
        return pair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_trade_on.pair
     *
     * @param pair the value for market_trade_on.pair
     *
     * @mbg.generated
     */
    public void setPair(String pair) {
        this.pair = pair == null ? null : pair.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_trade_on.price_display
     *
     * @return the value of market_trade_on.price_display
     *
     * @mbg.generated
     */
    public String getPriceDisplay() {
        return priceDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_trade_on.price_display
     *
     * @param priceDisplay the value for market_trade_on.price_display
     *
     * @mbg.generated
     */
    public void setPriceDisplay(String priceDisplay) {
        this.priceDisplay = priceDisplay == null ? null : priceDisplay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_trade_on.hr_price_display
     *
     * @return the value of market_trade_on.hr_price_display
     *
     * @mbg.generated
     */
    public String getHrPriceDisplay() {
        return hrPriceDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_trade_on.hr_price_display
     *
     * @param hrPriceDisplay the value for market_trade_on.hr_price_display
     *
     * @mbg.generated
     */
    public void setHrPriceDisplay(String hrPriceDisplay) {
        this.hrPriceDisplay = hrPriceDisplay == null ? null : hrPriceDisplay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_trade_on.percent_change_display
     *
     * @return the value of market_trade_on.percent_change_display
     *
     * @mbg.generated
     */
    public BigDecimal getPercentChangeDisplay() {
        return percentChangeDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_trade_on.percent_change_display
     *
     * @param percentChangeDisplay the value for market_trade_on.percent_change_display
     *
     * @mbg.generated
     */
    public void setPercentChangeDisplay(BigDecimal percentChangeDisplay) {
        this.percentChangeDisplay = percentChangeDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_trade_on.market_alias
     *
     * @return the value of market_trade_on.market_alias
     *
     * @mbg.generated
     */
    public String getMarketAlias() {
        return marketAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_trade_on.market_alias
     *
     * @param marketAlias the value for market_trade_on.market_alias
     *
     * @mbg.generated
     */
    public void setMarketAlias(String marketAlias) {
        this.marketAlias = marketAlias == null ? null : marketAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_trade_on.create_time
     *
     * @return the value of market_trade_on.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_trade_on.create_time
     *
     * @param createTime the value for market_trade_on.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_trade_on.logo
     *
     * @return the value of market_trade_on.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_trade_on.logo
     *
     * @param logo the value for market_trade_on.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_trade_on.price
     *
     * @return the value of market_trade_on.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_trade_on.price
     *
     * @param price the value for market_trade_on.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}