package com.blockchain.commune.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;


@JsonIgnoreProperties(ignoreUnknown = true)
public class MarketExchangeInfo implements Serializable {
    private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.exchange_name
     *
     * @mbg.generated
     */
    @JsonProperty("exchange_name")
    private String exchangeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.exchange_code
     *
     * @mbg.generated
     */
    @JsonProperty("exchange_code")
    private String exchangeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.currency_name
     *
     * @mbg.generated
     */
    @JsonProperty("currency_name")
    private String currencyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.currency_code
     *
     * @mbg.generated
     */
    @JsonProperty("currency_code")
    private String currencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.last
     *
     * @mbg.generated
     */
    private String last;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.high
     *
     * @mbg.generated
     */
    private String high;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.low
     *
     * @mbg.generated
     */
    private String low;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.degree
     *
     * @mbg.generated
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.vol
     *
     * @mbg.generated
     */
    private String vol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.domain
     *
     * @mbg.generated
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.k_line
     *
     * @mbg.generated
     */
    private String kLine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_exchange_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    private String[] line;

    public String[] getLine() {
        return line;
    }

    public void setLine(String[] line) {
        this.line = line;
    }

    public MarketExchangeInfo() {
    }

    @Override
    public String toString() {
        return "MarketExchangeInfo{" +
                "id='" + id + '\'' +
                ", exchangeName='" + exchangeName + '\'' +
                ", exchangeCode='" + exchangeCode + '\'' +
                ", currencyName='" + currencyName + '\'' +
                ", currencyCode='" + currencyCode + '\'' +
                ", logo='" + logo + '\'' +
                ", sort='" + sort + '\'' +
                ", last='" + last + '\'' +
                ", high='" + high + '\'' +
                ", low='" + low + '\'' +
                ", degree='" + degree + '\'' +
                ", vol='" + vol + '\'' +
                ", domain='" + domain + '\'' +
                ", kLine='" + kLine + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", line=" + Arrays.toString(line) +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.id
     *
     * @return the value of market_exchange_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.id
     *
     * @param id the value for market_exchange_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.exchange_name
     *
     * @return the value of market_exchange_info.exchange_name
     *
     * @mbg.generated
     */
    public String getExchangeName() {
        return exchangeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.exchange_name
     *
     * @param exchangeName the value for market_exchange_info.exchange_name
     *
     * @mbg.generated
     */
    public void setExchangeName(String exchangeName) {
        this.exchangeName = exchangeName == null ? null : exchangeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.exchange_code
     *
     * @return the value of market_exchange_info.exchange_code
     *
     * @mbg.generated
     */
    public String getExchangeCode() {
        return exchangeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.exchange_code
     *
     * @param exchangeCode the value for market_exchange_info.exchange_code
     *
     * @mbg.generated
     */
    public void setExchangeCode(String exchangeCode) {
        this.exchangeCode = exchangeCode == null ? null : exchangeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.currency_name
     *
     * @return the value of market_exchange_info.currency_name
     *
     * @mbg.generated
     */
    public String getCurrencyName() {
        return currencyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.currency_name
     *
     * @param currencyName the value for market_exchange_info.currency_name
     *
     * @mbg.generated
     */
    public void setCurrencyName(String currencyName) {
        this.currencyName = currencyName == null ? null : currencyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.currency_code
     *
     * @return the value of market_exchange_info.currency_code
     *
     * @mbg.generated
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.currency_code
     *
     * @param currencyCode the value for market_exchange_info.currency_code
     *
     * @mbg.generated
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode == null ? null : currencyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.logo
     *
     * @return the value of market_exchange_info.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.logo
     *
     * @param logo the value for market_exchange_info.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.sort
     *
     * @return the value of market_exchange_info.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.sort
     *
     * @param sort the value for market_exchange_info.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.last
     *
     * @return the value of market_exchange_info.last
     *
     * @mbg.generated
     */
    public String getLast() {
        return last;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.last
     *
     * @param last the value for market_exchange_info.last
     *
     * @mbg.generated
     */
    public void setLast(String last) {
        this.last = last == null ? null : last.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.high
     *
     * @return the value of market_exchange_info.high
     *
     * @mbg.generated
     */
    public String getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.high
     *
     * @param high the value for market_exchange_info.high
     *
     * @mbg.generated
     */
    public void setHigh(String high) {
        this.high = high == null ? null : high.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.low
     *
     * @return the value of market_exchange_info.low
     *
     * @mbg.generated
     */
    public String getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.low
     *
     * @param low the value for market_exchange_info.low
     *
     * @mbg.generated
     */
    public void setLow(String low) {
        this.low = low == null ? null : low.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.degree
     *
     * @return the value of market_exchange_info.degree
     *
     * @mbg.generated
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.degree
     *
     * @param degree the value for market_exchange_info.degree
     *
     * @mbg.generated
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.vol
     *
     * @return the value of market_exchange_info.vol
     *
     * @mbg.generated
     */
    public String getVol() {
        return vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.vol
     *
     * @param vol the value for market_exchange_info.vol
     *
     * @mbg.generated
     */
    public void setVol(String vol) {
        this.vol = vol == null ? null : vol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.domain
     *
     * @return the value of market_exchange_info.domain
     *
     * @mbg.generated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.domain
     *
     * @param domain the value for market_exchange_info.domain
     *
     * @mbg.generated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.k_line
     *
     * @return the value of market_exchange_info.k_line
     *
     * @mbg.generated
     */
    public String getkLine() {
        return kLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.k_line
     *
     * @param kLine the value for market_exchange_info.k_line
     *
     * @mbg.generated
     */
    public void setkLine(String kLine) {
        this.kLine = kLine == null ? null : kLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.create_time
     *
     * @return the value of market_exchange_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.create_time
     *
     * @param createTime the value for market_exchange_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_exchange_info.update_time
     *
     * @return the value of market_exchange_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_exchange_info.update_time
     *
     * @param updateTime the value for market_exchange_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}