package com.blockchain.commune.model;

import java.math.BigDecimal;
import java.util.Date;

public class ReadRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_record.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_record.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_record.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_record.post_Id
     *
     * @mbg.generated
     */
    private String postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_record.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_record.score
     *
     * @mbg.generated
     */
    private BigDecimal score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_record.score_status
     *
     * @mbg.generated
     */
    private Byte scoreStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_record.verify_status
     *
     * @mbg.generated
     */
    private Byte verifyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column read_record.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_record.id
     *
     * @return the value of read_record.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_record.id
     *
     * @param id the value for read_record.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_record.user_id
     *
     * @return the value of read_record.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_record.user_id
     *
     * @param userId the value for read_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_record.user_name
     *
     * @return the value of read_record.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_record.user_name
     *
     * @param userName the value for read_record.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_record.post_Id
     *
     * @return the value of read_record.post_Id
     *
     * @mbg.generated
     */
    public String getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_record.post_Id
     *
     * @param postId the value for read_record.post_Id
     *
     * @mbg.generated
     */
    public void setPostId(String postId) {
        this.postId = postId == null ? null : postId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_record.title
     *
     * @return the value of read_record.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_record.title
     *
     * @param title the value for read_record.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_record.score
     *
     * @return the value of read_record.score
     *
     * @mbg.generated
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_record.score
     *
     * @param score the value for read_record.score
     *
     * @mbg.generated
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_record.score_status
     *
     * @return the value of read_record.score_status
     *
     * @mbg.generated
     */
    public Byte getScoreStatus() {
        return scoreStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_record.score_status
     *
     * @param scoreStatus the value for read_record.score_status
     *
     * @mbg.generated
     */
    public void setScoreStatus(Byte scoreStatus) {
        this.scoreStatus = scoreStatus ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_record.verify_status
     *
     * @return the value of read_record.verify_status
     *
     * @mbg.generated
     */
    public Byte getVerifyStatus() {
        return verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_record.verify_status
     *
     * @param verifyStatus the value for read_record.verify_status
     *
     * @mbg.generated
     */
    public void setVerifyStatus(Byte verifyStatus) {
        this.verifyStatus = verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_record.create_time
     *
     * @return the value of read_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_record.create_time
     *
     * @param createTime the value for read_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column read_record.update_time
     *
     * @return the value of read_record.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column read_record.update_time
     *
     * @param updateTime the value for read_record.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}