package com.blockchain.commune.model;

import java.util.Date;

public class SmsCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_code.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_code.sms_code
     *
     * @mbg.generated
     */
    private String smsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_code.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_code.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_code.mobile
     *
     * @return the value of sms_code.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_code.mobile
     *
     * @param mobile the value for sms_code.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_code.sms_code
     *
     * @return the value of sms_code.sms_code
     *
     * @mbg.generated
     */
    public String getSmsCode() {
        return smsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_code.sms_code
     *
     * @param smsCode the value for sms_code.sms_code
     *
     * @mbg.generated
     */
    public void setSmsCode(String smsCode) {
        this.smsCode = smsCode == null ? null : smsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_code.type
     *
     * @return the value of sms_code.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_code.type
     *
     * @param type the value for sms_code.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_code.create_time
     *
     * @return the value of sms_code.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_code.create_time
     *
     * @param createTime the value for sms_code.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}