package com.blockchain.commune.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_type
     *
     * @mbg.generated
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.vip_level
     *
     * @mbg.generated
     */
    private String vipLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_code
     *
     * @mbg.generated
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.recommend_id
     *
     * @mbg.generated
     */
    private String recommendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_name
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_icon
     *
     * @mbg.generated
     */
    private String userIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.google_AuthKey
     *
     * @mbg.generated
     */
    private String googleAuthkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.validate
     *
     * @mbg.generated
     */
    private Byte validate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_method
     *
     * @mbg.generated
     */
    private String loginMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.auth_method
     *
     * @mbg.generated
     */
    private String authMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_type
     *
     * @return the value of user.user_type
     *
     * @mbg.generated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_type
     *
     * @param userType the value for user.user_type
     *
     * @mbg.generated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.vip_level
     *
     * @return the value of user.vip_level
     *
     * @mbg.generated
     */
    public String getVipLevel() {
        return vipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.vip_level
     *
     * @param vipLevel the value for user.vip_level
     *
     * @mbg.generated
     */
    public void setVipLevel(String vipLevel) {
        this.vipLevel = vipLevel == null ? null : vipLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_code
     *
     * @return the value of user.user_code
     *
     * @mbg.generated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_code
     *
     * @param userCode the value for user.user_code
     *
     * @mbg.generated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.recommend_id
     *
     * @return the value of user.recommend_id
     *
     * @mbg.generated
     */
    public String getRecommendId() {
        return recommendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.recommend_id
     *
     * @param recommendId the value for user.recommend_id
     *
     * @mbg.generated
     */
    public void setRecommendId(String recommendId) {
        this.recommendId = recommendId == null ? null : recommendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_name
     *
     * @return the value of user.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_name
     *
     * @param loginName the value for user.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nick_name
     *
     * @return the value of user.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nick_name
     *
     * @param nickName the value for user.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_icon
     *
     * @return the value of user.user_icon
     *
     * @mbg.generated
     */
    public String getUserIcon() {
        return userIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_icon
     *
     * @param userIcon the value for user.user_icon
     *
     * @mbg.generated
     */
    public void setUserIcon(String userIcon) {
        this.userIcon = userIcon == null ? null : userIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.google_AuthKey
     *
     * @return the value of user.google_AuthKey
     *
     * @mbg.generated
     */
    public String getGoogleAuthkey() {
        return googleAuthkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.google_AuthKey
     *
     * @param googleAuthkey the value for user.google_AuthKey
     *
     * @mbg.generated
     */
    public void setGoogleAuthkey(String googleAuthkey) {
        this.googleAuthkey = googleAuthkey == null ? null : googleAuthkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.validate
     *
     * @return the value of user.validate
     *
     * @mbg.generated
     */
    public Byte getValidate() {
        return validate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.validate
     *
     * @param validate the value for user.validate
     *
     * @mbg.generated
     */
    public void setValidate(Byte validate) {
        this.validate = validate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.open_id
     *
     * @return the value of user.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.open_id
     *
     * @param openId the value for user.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_method
     *
     * @return the value of user.login_method
     *
     * @mbg.generated
     */
    public String getLoginMethod() {
        return loginMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_method
     *
     * @param loginMethod the value for user.login_method
     *
     * @mbg.generated
     */
    public void setLoginMethod(String loginMethod) {
        this.loginMethod = loginMethod == null ? null : loginMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.auth_method
     *
     * @return the value of user.auth_method
     *
     * @mbg.generated
     */
    public String getAuthMethod() {
        return authMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.auth_method
     *
     * @param authMethod the value for user.auth_method
     *
     * @mbg.generated
     */
    public void setAuthMethod(String authMethod) {
        this.authMethod = authMethod == null ? null : authMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_time
     *
     * @return the value of user.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_time
     *
     * @param updateTime the value for user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}