package com.blockchain.commune.model;

import java.util.Date;

public class UserRecommendedCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recommended_code.recommended_code
     *
     * @mbg.generated
     */
    private String recommendedCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recommended_code.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recommended_code.recommended_url
     *
     * @mbg.generated
     */
    private String recommendedUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recommended_code.recommended_qrcode
     *
     * @mbg.generated
     */
    private String recommendedQrcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recommended_code.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_recommended_code.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recommended_code.recommended_code
     *
     * @return the value of user_recommended_code.recommended_code
     *
     * @mbg.generated
     */
    public String getRecommendedCode() {
        return recommendedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recommended_code.recommended_code
     *
     * @param recommendedCode the value for user_recommended_code.recommended_code
     *
     * @mbg.generated
     */
    public void setRecommendedCode(String recommendedCode) {
        this.recommendedCode = recommendedCode == null ? null : recommendedCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recommended_code.user_id
     *
     * @return the value of user_recommended_code.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recommended_code.user_id
     *
     * @param userId the value for user_recommended_code.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recommended_code.recommended_url
     *
     * @return the value of user_recommended_code.recommended_url
     *
     * @mbg.generated
     */
    public String getRecommendedUrl() {
        return recommendedUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recommended_code.recommended_url
     *
     * @param recommendedUrl the value for user_recommended_code.recommended_url
     *
     * @mbg.generated
     */
    public void setRecommendedUrl(String recommendedUrl) {
        this.recommendedUrl = recommendedUrl == null ? null : recommendedUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recommended_code.recommended_qrcode
     *
     * @return the value of user_recommended_code.recommended_qrcode
     *
     * @mbg.generated
     */
    public String getRecommendedQrcode() {
        return recommendedQrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recommended_code.recommended_qrcode
     *
     * @param recommendedQrcode the value for user_recommended_code.recommended_qrcode
     *
     * @mbg.generated
     */
    public void setRecommendedQrcode(String recommendedQrcode) {
        this.recommendedQrcode = recommendedQrcode == null ? null : recommendedQrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recommended_code.update_time
     *
     * @return the value of user_recommended_code.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recommended_code.update_time
     *
     * @param updateTime the value for user_recommended_code.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_recommended_code.create_time
     *
     * @return the value of user_recommended_code.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_recommended_code.create_time
     *
     * @param createTime the value for user_recommended_code.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}