package com.blockchain.commune.mapper;

import com.blockchain.commune.model.Advertisement;
import com.blockchain.commune.model.AdvertisementCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AdvertisementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    @SelectProvider(type=AdvertisementSqlProvider.class, method="countByExample")
    long countByExample(AdvertisementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    @DeleteProvider(type=AdvertisementSqlProvider.class, method="deleteByExample")
    int deleteByExample(AdvertisementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    @Delete({
        "delete from advertisement",
        "where ad_id = #{adId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    @Insert({
        "insert into advertisement (ad_id, news_id, ",
        "ad_context, user_id, ",
        "name, price, total_price, ",
        "last_price, comment_num, ",
        "create_time, update_time, ",
        "status, remark, ",
        "user_icon)",
        "values (#{adId,jdbcType=VARCHAR}, #{newsId,jdbcType=VARCHAR}, ",
        "#{adContext,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{price,jdbcType=DECIMAL}, #{totalPrice,jdbcType=DECIMAL}, ",
        "#{lastPrice,jdbcType=DECIMAL}, #{commentNum,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=TINYINT}, #{remark,jdbcType=VARCHAR}, ",
        "#{userIcon,jdbcType=VARCHAR})"
    })
    int insert(Advertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    @InsertProvider(type=AdvertisementSqlProvider.class, method="insertSelective")
    int insertSelective(Advertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    @SelectProvider(type=AdvertisementSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ad_id", property="adId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="news_id", property="newsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="ad_context", property="adContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="total_price", property="totalPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="last_price", property="lastPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="comment_num", property="commentNum", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_icon", property="userIcon", jdbcType=JdbcType.VARCHAR)
    })
    List<Advertisement> selectByExample(AdvertisementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ad_id, news_id, ad_context, user_id, name, price, total_price, last_price, comment_num, ",
        "create_time, update_time, status, remark, user_icon",
        "from advertisement",
        "where ad_id = #{adId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ad_id", property="adId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="news_id", property="newsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="ad_context", property="adContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="total_price", property="totalPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="last_price", property="lastPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="comment_num", property="commentNum", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_icon", property="userIcon", jdbcType=JdbcType.VARCHAR)
    })
    Advertisement selectByPrimaryKey(String adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AdvertisementSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Advertisement record, @Param("example") AdvertisementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AdvertisementSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Advertisement record, @Param("example") AdvertisementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AdvertisementSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Advertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated
     */
    @Update({
        "update advertisement",
        "set news_id = #{newsId,jdbcType=VARCHAR},",
          "ad_context = #{adContext,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "total_price = #{totalPrice,jdbcType=DECIMAL},",
          "last_price = #{lastPrice,jdbcType=DECIMAL},",
          "comment_num = #{commentNum,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=TINYINT},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "user_icon = #{userIcon,jdbcType=VARCHAR}",
        "where ad_id = #{adId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Advertisement record);
}