package com.blockchain.commune.mapper;

import com.blockchain.commune.model.ApkUpdateInfo;
import com.blockchain.commune.model.ApkUpdateInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ApkUpdateInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apk_update_info
     *
     * @mbg.generated
     */
    @SelectProvider(type=ApkUpdateInfoSqlProvider.class, method="countByExample")
    long countByExample(ApkUpdateInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apk_update_info
     *
     * @mbg.generated
     */
    @DeleteProvider(type=ApkUpdateInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(ApkUpdateInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apk_update_info
     *
     * @mbg.generated
     */
    @Delete({
        "delete from apk_update_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apk_update_info
     *
     * @mbg.generated
     */
    @Insert({
        "insert into apk_update_info (id, new_version, ",
        "mini_version, apk_qrcode, ",
        "apk_url, apk_desc, ",
        "platform, create_time, ",
        "version_code)",
        "values (#{id,jdbcType=INTEGER}, #{newVersion,jdbcType=VARCHAR}, ",
        "#{miniVersion,jdbcType=INTEGER}, #{apkQrcode,jdbcType=VARCHAR}, ",
        "#{apkUrl,jdbcType=VARCHAR}, #{apkDesc,jdbcType=VARCHAR}, ",
        "#{platform,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{versionCode,jdbcType=INTEGER})"
    })
    int insert(ApkUpdateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apk_update_info
     *
     * @mbg.generated
     */
    @InsertProvider(type=ApkUpdateInfoSqlProvider.class, method="insertSelective")
    int insertSelective(ApkUpdateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apk_update_info
     *
     * @mbg.generated
     */
    @SelectProvider(type=ApkUpdateInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="new_version", property="newVersion", jdbcType=JdbcType.VARCHAR),
        @Result(column="mini_version", property="miniVersion", jdbcType=JdbcType.INTEGER),
        @Result(column="apk_qrcode", property="apkQrcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="apk_url", property="apkUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="apk_desc", property="apkDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="platform", property="platform", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="version_code", property="versionCode", jdbcType=JdbcType.INTEGER)
    })
    List<ApkUpdateInfo> selectByExample(ApkUpdateInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apk_update_info
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, new_version, mini_version, apk_qrcode, apk_url, apk_desc, platform, create_time, ",
        "version_code",
        "from apk_update_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="new_version", property="newVersion", jdbcType=JdbcType.VARCHAR),
        @Result(column="mini_version", property="miniVersion", jdbcType=JdbcType.INTEGER),
        @Result(column="apk_qrcode", property="apkQrcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="apk_url", property="apkUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="apk_desc", property="apkDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="platform", property="platform", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="version_code", property="versionCode", jdbcType=JdbcType.INTEGER)
    })
    ApkUpdateInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apk_update_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ApkUpdateInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ApkUpdateInfo record, @Param("example") ApkUpdateInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apk_update_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ApkUpdateInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ApkUpdateInfo record, @Param("example") ApkUpdateInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apk_update_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ApkUpdateInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ApkUpdateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apk_update_info
     *
     * @mbg.generated
     */
    @Update({
        "update apk_update_info",
        "set new_version = #{newVersion,jdbcType=VARCHAR},",
          "mini_version = #{miniVersion,jdbcType=INTEGER},",
          "apk_qrcode = #{apkQrcode,jdbcType=VARCHAR},",
          "apk_url = #{apkUrl,jdbcType=VARCHAR},",
          "apk_desc = #{apkDesc,jdbcType=VARCHAR},",
          "platform = #{platform,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "version_code = #{versionCode,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ApkUpdateInfo record);
}