package com.blockchain.commune.mapper;

import com.blockchain.commune.model.CoinDetail;
import com.blockchain.commune.model.CoinDetailCriteria.Criteria;
import com.blockchain.commune.model.CoinDetailCriteria.Criterion;
import com.blockchain.commune.model.CoinDetailCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class CoinDetailSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_detail
     *
     * @mbg.generated
     */
    public String countByExample(CoinDetailCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("coin_detail");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_detail
     *
     * @mbg.generated
     */
    public String deleteByExample(CoinDetailCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("coin_detail");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_detail
     *
     * @mbg.generated
     */
    public String insertSelective(CoinDetail record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("coin_detail");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getCoinName() != null) {
            sql.VALUES("coin_name", "#{coinName,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrencyCode() != null) {
            sql.VALUES("currency_code", "#{currencyCode,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinIntroduction() != null) {
            sql.VALUES("coin_introduction", "#{coinIntroduction,jdbcType=VARCHAR}");
        }
        
        if (record.getBaseInfoList() != null) {
            sql.VALUES("base_info_list", "#{baseInfoList,jdbcType=VARCHAR}");
        }
        
        if (record.getBatch() != null) {
            sql.VALUES("batch", "#{batch,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_detail
     *
     * @mbg.generated
     */
    public String selectByExample(CoinDetailCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("coin_name");
        sql.SELECT("currency_code");
        sql.SELECT("coin_introduction");
        sql.SELECT("base_info_list");
        sql.SELECT("batch");
        sql.SELECT("create_time");
        sql.FROM("coin_detail");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_detail
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CoinDetail record = (CoinDetail) parameter.get("record");
        CoinDetailCriteria example = (CoinDetailCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("coin_detail");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getCoinName() != null) {
            sql.SET("coin_name = #{record.coinName,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrencyCode() != null) {
            sql.SET("currency_code = #{record.currencyCode,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinIntroduction() != null) {
            sql.SET("coin_introduction = #{record.coinIntroduction,jdbcType=VARCHAR}");
        }
        
        if (record.getBaseInfoList() != null) {
            sql.SET("base_info_list = #{record.baseInfoList,jdbcType=VARCHAR}");
        }
        
        if (record.getBatch() != null) {
            sql.SET("batch = #{record.batch,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_detail
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("coin_detail");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("coin_name = #{record.coinName,jdbcType=VARCHAR}");
        sql.SET("currency_code = #{record.currencyCode,jdbcType=VARCHAR}");
        sql.SET("coin_introduction = #{record.coinIntroduction,jdbcType=VARCHAR}");
        sql.SET("base_info_list = #{record.baseInfoList,jdbcType=VARCHAR}");
        sql.SET("batch = #{record.batch,jdbcType=INTEGER}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        
        CoinDetailCriteria example = (CoinDetailCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_detail
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(CoinDetail record) {
        SQL sql = new SQL();
        sql.UPDATE("coin_detail");
        
        if (record.getCoinName() != null) {
            sql.SET("coin_name = #{coinName,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrencyCode() != null) {
            sql.SET("currency_code = #{currencyCode,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinIntroduction() != null) {
            sql.SET("coin_introduction = #{coinIntroduction,jdbcType=VARCHAR}");
        }
        
        if (record.getBaseInfoList() != null) {
            sql.SET("base_info_list = #{baseInfoList,jdbcType=VARCHAR}");
        }
        
        if (record.getBatch() != null) {
            sql.SET("batch = #{batch,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_detail
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, CoinDetailCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}