package com.blockchain.commune.mapper;

import com.blockchain.commune.model.CommentReplay;
import com.blockchain.commune.model.CommentReplayCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CommentReplayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_replay
     *
     * @mbg.generated
     */
    @SelectProvider(type=CommentReplaySqlProvider.class, method="countByExample")
    long countByExample(CommentReplayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_replay
     *
     * @mbg.generated
     */
    @DeleteProvider(type=CommentReplaySqlProvider.class, method="deleteByExample")
    int deleteByExample(CommentReplayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_replay
     *
     * @mbg.generated
     */
    @Delete({
        "delete from comment_replay",
        "where replay_id = #{replayId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String replayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_replay
     *
     * @mbg.generated
     */
    @Insert({
        "insert into comment_replay (replay_id, comment_id, ",
        "user_id, name, replay_context, ",
        "re_user_id, re_name, ",
        "create_time, user_icon)",
        "values (#{replayId,jdbcType=VARCHAR}, #{commentId,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, #{replayContext,jdbcType=VARCHAR}, ",
        "#{reUserId,jdbcType=VARCHAR}, #{reName,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{userIcon,jdbcType=VARCHAR})"
    })
    int insert(CommentReplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_replay
     *
     * @mbg.generated
     */
    @InsertProvider(type=CommentReplaySqlProvider.class, method="insertSelective")
    int insertSelective(CommentReplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_replay
     *
     * @mbg.generated
     */
    @SelectProvider(type=CommentReplaySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="replay_id", property="replayId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="comment_id", property="commentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="replay_context", property="replayContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="re_user_id", property="reUserId", jdbcType=JdbcType.VARCHAR),
        @Result(column="re_name", property="reName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user_icon", property="userIcon", jdbcType=JdbcType.VARCHAR)
    })
    List<CommentReplay> selectByExample(CommentReplayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_replay
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "replay_id, comment_id, user_id, name, replay_context, re_user_id, re_name, create_time, ",
        "user_icon",
        "from comment_replay",
        "where replay_id = #{replayId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="replay_id", property="replayId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="comment_id", property="commentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="replay_context", property="replayContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="re_user_id", property="reUserId", jdbcType=JdbcType.VARCHAR),
        @Result(column="re_name", property="reName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user_icon", property="userIcon", jdbcType=JdbcType.VARCHAR)
    })
    CommentReplay selectByPrimaryKey(String replayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_replay
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommentReplaySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CommentReplay record, @Param("example") CommentReplayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_replay
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommentReplaySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CommentReplay record, @Param("example") CommentReplayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_replay
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommentReplaySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CommentReplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_replay
     *
     * @mbg.generated
     */
    @Update({
        "update comment_replay",
        "set comment_id = #{commentId,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "replay_context = #{replayContext,jdbcType=VARCHAR},",
          "re_user_id = #{reUserId,jdbcType=VARCHAR},",
          "re_name = #{reName,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "user_icon = #{userIcon,jdbcType=VARCHAR}",
        "where replay_id = #{replayId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(CommentReplay record);
}