package com.blockchain.commune.mapper;

import com.blockchain.commune.model.CommentGreat;
import com.blockchain.commune.model.CommentGreatCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CommentGreatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_great
     *
     * @mbg.generated
     */
    @SelectProvider(type=CommentGreatSqlProvider.class, method="countByExample")
    long countByExample(CommentGreatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_great
     *
     * @mbg.generated
     */
    @DeleteProvider(type=CommentGreatSqlProvider.class, method="deleteByExample")
    int deleteByExample(CommentGreatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_great
     *
     * @mbg.generated
     */
    @Delete({
        "delete from comment_great",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_great
     *
     * @mbg.generated
     */
    @Insert({
        "insert into comment_great (id, comment_id, ",
        "user_id, create_time)",
        "values (#{id,jdbcType=VARCHAR}, #{commentId,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(CommentGreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_great
     *
     * @mbg.generated
     */
    @InsertProvider(type=CommentGreatSqlProvider.class, method="insertSelective")
    int insertSelective(CommentGreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_great
     *
     * @mbg.generated
     */
    @SelectProvider(type=CommentGreatSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="comment_id", property="commentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<CommentGreat> selectByExample(CommentGreatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_great
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, comment_id, user_id, create_time",
        "from comment_great",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="comment_id", property="commentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    CommentGreat selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_great
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommentGreatSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CommentGreat record, @Param("example") CommentGreatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_great
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommentGreatSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CommentGreat record, @Param("example") CommentGreatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_great
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommentGreatSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CommentGreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_great
     *
     * @mbg.generated
     */
    @Update({
        "update comment_great",
        "set comment_id = #{commentId,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(CommentGreat record);
}