package com.blockchain.commune.mapper;

import com.blockchain.commune.model.MarketExchangeInfo;
import com.blockchain.commune.model.MarketExchangeInfoCriteria.Criteria;
import com.blockchain.commune.model.MarketExchangeInfoCriteria.Criterion;
import com.blockchain.commune.model.MarketExchangeInfoCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class MarketExchangeInfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange_info
     *
     * @mbg.generated
     */
    public String countByExample(MarketExchangeInfoCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("market_exchange_info");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange_info
     *
     * @mbg.generated
     */
    public String deleteByExample(MarketExchangeInfoCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("market_exchange_info");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange_info
     *
     * @mbg.generated
     */
    public String insertSelective(MarketExchangeInfo record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("market_exchange_info");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getExchangeName() != null) {
            sql.VALUES("exchange_name", "#{exchangeName,jdbcType=VARCHAR}");
        }
        
        if (record.getExchangeCode() != null) {
            sql.VALUES("exchange_code", "#{exchangeCode,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrencyName() != null) {
            sql.VALUES("currency_name", "#{currencyName,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrencyCode() != null) {
            sql.VALUES("currency_code", "#{currencyCode,jdbcType=VARCHAR}");
        }
        
        if (record.getLogo() != null) {
            sql.VALUES("logo", "#{logo,jdbcType=VARCHAR}");
        }
        
        if (record.getSort() != null) {
            sql.VALUES("sort", "#{sort,jdbcType=INTEGER}");
        }
        
        if (record.getLast() != null) {
            sql.VALUES("last", "#{last,jdbcType=VARCHAR}");
        }
        
        if (record.getHigh() != null) {
            sql.VALUES("high", "#{high,jdbcType=VARCHAR}");
        }
        
        if (record.getLow() != null) {
            sql.VALUES("low", "#{low,jdbcType=VARCHAR}");
        }
        
        if (record.getDegree() != null) {
            sql.VALUES("degree", "#{degree,jdbcType=VARCHAR}");
        }
        
        if (record.getVol() != null) {
            sql.VALUES("vol", "#{vol,jdbcType=VARCHAR}");
        }
        
        if (record.getDomain() != null) {
            sql.VALUES("domain", "#{domain,jdbcType=VARCHAR}");
        }
        
        if (record.getkLine() != null) {
            sql.VALUES("k_line", "#{kLine,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange_info
     *
     * @mbg.generated
     */
    public String selectByExample(MarketExchangeInfoCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("exchange_name");
        sql.SELECT("exchange_code");
        sql.SELECT("currency_name");
        sql.SELECT("currency_code");
        sql.SELECT("logo");
        sql.SELECT("sort");
        sql.SELECT("last");
        sql.SELECT("high");
        sql.SELECT("low");
        sql.SELECT("degree");
        sql.SELECT("vol");
        sql.SELECT("domain");
        sql.SELECT("k_line");
        sql.SELECT("create_time");
        sql.SELECT("update_time");
        sql.FROM("market_exchange_info");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange_info
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MarketExchangeInfo record = (MarketExchangeInfo) parameter.get("record");
        MarketExchangeInfoCriteria example = (MarketExchangeInfoCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("market_exchange_info");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getExchangeName() != null) {
            sql.SET("exchange_name = #{record.exchangeName,jdbcType=VARCHAR}");
        }
        
        if (record.getExchangeCode() != null) {
            sql.SET("exchange_code = #{record.exchangeCode,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrencyName() != null) {
            sql.SET("currency_name = #{record.currencyName,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrencyCode() != null) {
            sql.SET("currency_code = #{record.currencyCode,jdbcType=VARCHAR}");
        }
        
        if (record.getLogo() != null) {
            sql.SET("logo = #{record.logo,jdbcType=VARCHAR}");
        }
        
        if (record.getSort() != null) {
            sql.SET("sort = #{record.sort,jdbcType=INTEGER}");
        }
        
        if (record.getLast() != null) {
            sql.SET("last = #{record.last,jdbcType=VARCHAR}");
        }
        
        if (record.getHigh() != null) {
            sql.SET("high = #{record.high,jdbcType=VARCHAR}");
        }
        
        if (record.getLow() != null) {
            sql.SET("low = #{record.low,jdbcType=VARCHAR}");
        }
        
        if (record.getDegree() != null) {
            sql.SET("degree = #{record.degree,jdbcType=VARCHAR}");
        }
        
        if (record.getVol() != null) {
            sql.SET("vol = #{record.vol,jdbcType=VARCHAR}");
        }
        
        if (record.getDomain() != null) {
            sql.SET("domain = #{record.domain,jdbcType=VARCHAR}");
        }
        
        if (record.getkLine() != null) {
            sql.SET("k_line = #{record.kLine,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange_info
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("market_exchange_info");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("exchange_name = #{record.exchangeName,jdbcType=VARCHAR}");
        sql.SET("exchange_code = #{record.exchangeCode,jdbcType=VARCHAR}");
        sql.SET("currency_name = #{record.currencyName,jdbcType=VARCHAR}");
        sql.SET("currency_code = #{record.currencyCode,jdbcType=VARCHAR}");
        sql.SET("logo = #{record.logo,jdbcType=VARCHAR}");
        sql.SET("sort = #{record.sort,jdbcType=INTEGER}");
        sql.SET("last = #{record.last,jdbcType=VARCHAR}");
        sql.SET("high = #{record.high,jdbcType=VARCHAR}");
        sql.SET("low = #{record.low,jdbcType=VARCHAR}");
        sql.SET("degree = #{record.degree,jdbcType=VARCHAR}");
        sql.SET("vol = #{record.vol,jdbcType=VARCHAR}");
        sql.SET("domain = #{record.domain,jdbcType=VARCHAR}");
        sql.SET("k_line = #{record.kLine,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        
        MarketExchangeInfoCriteria example = (MarketExchangeInfoCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange_info
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(MarketExchangeInfo record) {
        SQL sql = new SQL();
        sql.UPDATE("market_exchange_info");
        
        if (record.getExchangeName() != null) {
            sql.SET("exchange_name = #{exchangeName,jdbcType=VARCHAR}");
        }
        
        if (record.getExchangeCode() != null) {
            sql.SET("exchange_code = #{exchangeCode,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrencyName() != null) {
            sql.SET("currency_name = #{currencyName,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrencyCode() != null) {
            sql.SET("currency_code = #{currencyCode,jdbcType=VARCHAR}");
        }
        
        if (record.getLogo() != null) {
            sql.SET("logo = #{logo,jdbcType=VARCHAR}");
        }
        
        if (record.getSort() != null) {
            sql.SET("sort = #{sort,jdbcType=INTEGER}");
        }
        
        if (record.getLast() != null) {
            sql.SET("last = #{last,jdbcType=VARCHAR}");
        }
        
        if (record.getHigh() != null) {
            sql.SET("high = #{high,jdbcType=VARCHAR}");
        }
        
        if (record.getLow() != null) {
            sql.SET("low = #{low,jdbcType=VARCHAR}");
        }
        
        if (record.getDegree() != null) {
            sql.SET("degree = #{degree,jdbcType=VARCHAR}");
        }
        
        if (record.getVol() != null) {
            sql.SET("vol = #{vol,jdbcType=VARCHAR}");
        }
        
        if (record.getDomain() != null) {
            sql.SET("domain = #{domain,jdbcType=VARCHAR}");
        }
        
        if (record.getkLine() != null) {
            sql.SET("k_line = #{kLine,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange_info
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, MarketExchangeInfoCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}