package com.blockchain.commune.mapper;

import com.blockchain.commune.model.MarketTag;
import com.blockchain.commune.model.MarketTagCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MarketTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tag
     *
     * @mbg.generated
     */
    @SelectProvider(type=MarketTagSqlProvider.class, method="countByExample")
    long countByExample(MarketTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tag
     *
     * @mbg.generated
     */
    @DeleteProvider(type=MarketTagSqlProvider.class, method="deleteByExample")
    int deleteByExample(MarketTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tag
     *
     * @mbg.generated
     */
    @Delete({
        "delete from market_tag",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tag
     *
     * @mbg.generated
     */
    @Insert({
        "insert into market_tag (id, tag, ",
        "uri, tag_type, disable, ",
        "create_time, update_time)",
        "values (#{id,jdbcType=VARCHAR}, #{tag,jdbcType=VARCHAR}, ",
        "#{uri,jdbcType=VARCHAR}, #{tagType,jdbcType=VARCHAR}, #{disable,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(MarketTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tag
     *
     * @mbg.generated
     */
    @InsertProvider(type=MarketTagSqlProvider.class, method="insertSelective")
    int insertSelective(MarketTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tag
     *
     * @mbg.generated
     */
    @SelectProvider(type=MarketTagSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="tag", property="tag", jdbcType=JdbcType.VARCHAR),
        @Result(column="uri", property="uri", jdbcType=JdbcType.VARCHAR),
        @Result(column="tag_type", property="tagType", jdbcType=JdbcType.VARCHAR),
        @Result(column="disable", property="disable", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<MarketTag> selectByExample(MarketTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tag
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, tag, uri, tag_type, disable, create_time, update_time",
        "from market_tag",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="tag", property="tag", jdbcType=JdbcType.VARCHAR),
        @Result(column="uri", property="uri", jdbcType=JdbcType.VARCHAR),
        @Result(column="tag_type", property="tagType", jdbcType=JdbcType.VARCHAR),
        @Result(column="disable", property="disable", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    MarketTag selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tag
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketTagSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MarketTag record, @Param("example") MarketTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tag
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketTagSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MarketTag record, @Param("example") MarketTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tag
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketTagSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MarketTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tag
     *
     * @mbg.generated
     */
    @Update({
        "update market_tag",
        "set tag = #{tag,jdbcType=VARCHAR},",
          "uri = #{uri,jdbcType=VARCHAR},",
          "tag_type = #{tagType,jdbcType=VARCHAR},",
          "disable = #{disable,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(MarketTag record);
}