package com.blockchain.commune.mapper;

import com.blockchain.commune.model.MarketTradeOnSpider;
import com.blockchain.commune.model.MarketTradeOnCriteria.Criteria;
import com.blockchain.commune.model.MarketTradeOnCriteria.Criterion;
import com.blockchain.commune.model.MarketTradeOnCriteria;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.jdbc.SQL;

public class MarketTradeOnSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_trade_on
     *
     * @mbg.generated
     */
    public String countByExample(MarketTradeOnCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("market_trade_on");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_trade_on
     *
     * @mbg.generated
     */
    public String deleteByExample(MarketTradeOnCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("market_trade_on");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_trade_on
     *
     * @mbg.generated
     */
    public String insertSelective(MarketTradeOnSpider record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("market_trade_on");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbol() != null) {
            sql.VALUES("symbol", "#{symbol,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketId() != null) {
            sql.VALUES("market_id", "#{marketId,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketName() != null) {
            sql.VALUES("market_name", "#{marketName,jdbcType=VARCHAR}");
        }
        
        if (record.getPair() != null) {
            sql.VALUES("pair", "#{pair,jdbcType=VARCHAR}");
        }
        
        if (record.getPriceDisplay() != null) {
            sql.VALUES("price_display", "#{priceDisplay,jdbcType=VARCHAR}");
        }
        
        if (record.getHrPriceDisplay() != null) {
            sql.VALUES("hr_price_display", "#{hrPriceDisplay,jdbcType=VARCHAR}");
        }
        
        if (record.getPercentChangeDisplay() != null) {
            sql.VALUES("percent_change_display", "#{percentChangeDisplay,jdbcType=DECIMAL}");
        }
        
        if (record.getMarketAlias() != null) {
            sql.VALUES("market_alias", "#{marketAlias,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getLogo() != null) {
            sql.VALUES("logo", "#{logo,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.VALUES("price", "#{price,jdbcType=DECIMAL}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_trade_on
     *
     * @mbg.generated
     */
    public String selectByExample(MarketTradeOnCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("symbol");
        sql.SELECT("market_id");
        sql.SELECT("market_name");
        sql.SELECT("pair");
        sql.SELECT("price_display");
        sql.SELECT("hr_price_display");
        sql.SELECT("percent_change_display");
        sql.SELECT("market_alias");
        sql.SELECT("create_time");
        sql.SELECT("logo");
        sql.SELECT("price");
        sql.FROM("market_trade_on");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_trade_on
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MarketTradeOnSpider record = (MarketTradeOnSpider) parameter.get("record");
        MarketTradeOnCriteria example = (MarketTradeOnCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("market_trade_on");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbol() != null) {
            sql.SET("symbol = #{record.symbol,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketId() != null) {
            sql.SET("market_id = #{record.marketId,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketName() != null) {
            sql.SET("market_name = #{record.marketName,jdbcType=VARCHAR}");
        }
        
        if (record.getPair() != null) {
            sql.SET("pair = #{record.pair,jdbcType=VARCHAR}");
        }
        
        if (record.getPriceDisplay() != null) {
            sql.SET("price_display = #{record.priceDisplay,jdbcType=VARCHAR}");
        }
        
        if (record.getHrPriceDisplay() != null) {
            sql.SET("hr_price_display = #{record.hrPriceDisplay,jdbcType=VARCHAR}");
        }
        
        if (record.getPercentChangeDisplay() != null) {
            sql.SET("percent_change_display = #{record.percentChangeDisplay,jdbcType=DECIMAL}");
        }
        
        if (record.getMarketAlias() != null) {
            sql.SET("market_alias = #{record.marketAlias,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getLogo() != null) {
            sql.SET("logo = #{record.logo,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{record.price,jdbcType=DECIMAL}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_trade_on
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("market_trade_on");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("symbol = #{record.symbol,jdbcType=VARCHAR}");
        sql.SET("market_id = #{record.marketId,jdbcType=VARCHAR}");
        sql.SET("market_name = #{record.marketName,jdbcType=VARCHAR}");
        sql.SET("pair = #{record.pair,jdbcType=VARCHAR}");
        sql.SET("price_display = #{record.priceDisplay,jdbcType=VARCHAR}");
        sql.SET("hr_price_display = #{record.hrPriceDisplay,jdbcType=VARCHAR}");
        sql.SET("percent_change_display = #{record.percentChangeDisplay,jdbcType=DECIMAL}");
        sql.SET("market_alias = #{record.marketAlias,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("logo = #{record.logo,jdbcType=VARCHAR}");
        sql.SET("price = #{record.price,jdbcType=DECIMAL}");
        
        MarketTradeOnCriteria example = (MarketTradeOnCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_trade_on
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(MarketTradeOnSpider record) {
        SQL sql = new SQL();
        sql.UPDATE("market_trade_on");
        
        if (record.getSymbol() != null) {
            sql.SET("symbol = #{symbol,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketId() != null) {
            sql.SET("market_id = #{marketId,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketName() != null) {
            sql.SET("market_name = #{marketName,jdbcType=VARCHAR}");
        }
        
        if (record.getPair() != null) {
            sql.SET("pair = #{pair,jdbcType=VARCHAR}");
        }
        
        if (record.getPriceDisplay() != null) {
            sql.SET("price_display = #{priceDisplay,jdbcType=VARCHAR}");
        }
        
        if (record.getHrPriceDisplay() != null) {
            sql.SET("hr_price_display = #{hrPriceDisplay,jdbcType=VARCHAR}");
        }
        
        if (record.getPercentChangeDisplay() != null) {
            sql.SET("percent_change_display = #{percentChangeDisplay,jdbcType=DECIMAL}");
        }
        
        if (record.getMarketAlias() != null) {
            sql.SET("market_alias = #{marketAlias,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getLogo() != null) {
            sql.SET("logo = #{logo,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{price,jdbcType=DECIMAL}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_trade_on
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, MarketTradeOnCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}