package com.blockchain.commune.mapper;

import com.blockchain.commune.model.MarketHot;
import com.blockchain.commune.model.MarketHotCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MarketHotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_hot
     *
     * @mbg.generated
     */
    @SelectProvider(type=MarketHotSqlProvider.class, method="countByExample")
    long countByExample(MarketHotCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_hot
     *
     * @mbg.generated
     */
    @DeleteProvider(type=MarketHotSqlProvider.class, method="deleteByExample")
    int deleteByExample(MarketHotCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_hot
     *
     * @mbg.generated
     */
    @Delete({
        "delete from market_hot",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_hot
     *
     * @mbg.generated
     */
    @Insert({
        "insert into market_hot (id, currency_name, ",
        "sort, create_time, ",
        "update_time)",
        "values (#{id,jdbcType=VARCHAR}, #{currencyName,jdbcType=VARCHAR}, ",
        "#{sort,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(MarketHot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_hot
     *
     * @mbg.generated
     */
    @InsertProvider(type=MarketHotSqlProvider.class, method="insertSelective")
    int insertSelective(MarketHot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_hot
     *
     * @mbg.generated
     */
    @SelectProvider(type=MarketHotSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="currency_name", property="currencyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort", property="sort", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<MarketHot> selectByExample(MarketHotCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_hot
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, currency_name, sort, create_time, update_time",
        "from market_hot",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="currency_name", property="currencyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort", property="sort", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    MarketHot selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_hot
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketHotSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MarketHot record, @Param("example") MarketHotCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_hot
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketHotSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MarketHot record, @Param("example") MarketHotCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_hot
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketHotSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MarketHot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_hot
     *
     * @mbg.generated
     */
    @Update({
        "update market_hot",
        "set currency_name = #{currencyName,jdbcType=VARCHAR},",
          "sort = #{sort,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(MarketHot record);
}