package com.blockchain.commune.mapper;

import com.blockchain.commune.model.MarketUserSelect;
import com.blockchain.commune.model.MarketUserSelectCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MarketUserSelectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user_select
     *
     * @mbg.generated
     */
    @SelectProvider(type=MarketUserSelectSqlProvider.class, method="countByExample")
    long countByExample(MarketUserSelectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user_select
     *
     * @mbg.generated
     */
    @DeleteProvider(type=MarketUserSelectSqlProvider.class, method="deleteByExample")
    int deleteByExample(MarketUserSelectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user_select
     *
     * @mbg.generated
     */
    @Delete({
        "delete from market_user_select",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user_select
     *
     * @mbg.generated
     */
    @Insert({
        "insert into market_user_select (id, user_id, ",
        "create_time, market_id)",
        "values (#{id,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{marketId,jdbcType=VARCHAR})"
    })
    int insert(MarketUserSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user_select
     *
     * @mbg.generated
     */
    @InsertProvider(type=MarketUserSelectSqlProvider.class, method="insertSelective")
    int insertSelective(MarketUserSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user_select
     *
     * @mbg.generated
     */
    @SelectProvider(type=MarketUserSelectSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="market_id", property="marketId", jdbcType=JdbcType.VARCHAR)
    })
    List<MarketUserSelect> selectByExample(MarketUserSelectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user_select
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, user_id, create_time, market_id",
        "from market_user_select",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="market_id", property="marketId", jdbcType=JdbcType.VARCHAR)
    })
    MarketUserSelect selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user_select
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketUserSelectSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MarketUserSelect record, @Param("example") MarketUserSelectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user_select
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketUserSelectSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MarketUserSelect record, @Param("example") MarketUserSelectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user_select
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketUserSelectSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MarketUserSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_user_select
     *
     * @mbg.generated
     */
    @Update({
        "update market_user_select",
        "set user_id = #{userId,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "market_id = #{marketId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(MarketUserSelect record);
}