package com.blockchain.commune.mapper;

import com.blockchain.commune.model.MarketCurrencyInfo;
import com.blockchain.commune.model.MarketCurrencyInfoCriteria.Criteria;
import com.blockchain.commune.model.MarketCurrencyInfoCriteria.Criterion;
import com.blockchain.commune.model.MarketCurrencyInfoCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class MarketCurrencyInfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_currency_info
     *
     * @mbg.generated
     */
    public String countByExample(MarketCurrencyInfoCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("market_currency_info");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_currency_info
     *
     * @mbg.generated
     */
    public String deleteByExample(MarketCurrencyInfoCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("market_currency_info");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_currency_info
     *
     * @mbg.generated
     */
    public String insertSelective(MarketCurrencyInfo record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("market_currency_info");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinName() != null) {
            sql.VALUES("coin_name", "#{coinName,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinImg() != null) {
            sql.VALUES("coin_img", "#{coinImg,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrencyCode() != null) {
            sql.VALUES("currency_code", "#{currencyCode,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketCap() != null) {
            sql.VALUES("market_cap", "#{marketCap,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.VALUES("price", "#{price,jdbcType=VARCHAR}");
        }
        
        if (record.getTurnover() != null) {
            sql.VALUES("turnover", "#{turnover,jdbcType=VARCHAR}");
        }
        
        if (record.getVolume() != null) {
            sql.VALUES("volume", "#{volume,jdbcType=VARCHAR}");
        }
        
        if (record.getChangepercent() != null) {
            sql.VALUES("changepercent", "#{changepercent,jdbcType=VARCHAR}");
        }
        
        if (record.getkLine() != null) {
            sql.VALUES("k_line", "#{kLine,jdbcType=VARCHAR}");
        }
        
        if (record.getCrawlStatus() != null) {
            sql.VALUES("crawl_status", "#{crawlStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getBatch() != null) {
            sql.VALUES("batch", "#{batch,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_currency_info
     *
     * @mbg.generated
     */
    public String selectByExample(MarketCurrencyInfoCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("coin_name");
        sql.SELECT("coin_img");
        sql.SELECT("currency_code");
        sql.SELECT("market_cap");
        sql.SELECT("price");
        sql.SELECT("turnover");
        sql.SELECT("volume");
        sql.SELECT("changepercent");
        sql.SELECT("k_line");
        sql.SELECT("crawl_status");
        sql.SELECT("batch");
        sql.SELECT("create_time");
        sql.SELECT("update_time");
        sql.FROM("market_currency_info");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_currency_info
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MarketCurrencyInfo record = (MarketCurrencyInfo) parameter.get("record");
        MarketCurrencyInfoCriteria example = (MarketCurrencyInfoCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("market_currency_info");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinName() != null) {
            sql.SET("coin_name = #{record.coinName,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinImg() != null) {
            sql.SET("coin_img = #{record.coinImg,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrencyCode() != null) {
            sql.SET("currency_code = #{record.currencyCode,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketCap() != null) {
            sql.SET("market_cap = #{record.marketCap,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{record.price,jdbcType=VARCHAR}");
        }
        
        if (record.getTurnover() != null) {
            sql.SET("turnover = #{record.turnover,jdbcType=VARCHAR}");
        }
        
        if (record.getVolume() != null) {
            sql.SET("volume = #{record.volume,jdbcType=VARCHAR}");
        }
        
        if (record.getChangepercent() != null) {
            sql.SET("changepercent = #{record.changepercent,jdbcType=VARCHAR}");
        }
        
        if (record.getkLine() != null) {
            sql.SET("k_line = #{record.kLine,jdbcType=VARCHAR}");
        }
        
        if (record.getCrawlStatus() != null) {
            sql.SET("crawl_status = #{record.crawlStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getBatch() != null) {
            sql.SET("batch = #{record.batch,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_currency_info
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("market_currency_info");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("coin_name = #{record.coinName,jdbcType=VARCHAR}");
        sql.SET("coin_img = #{record.coinImg,jdbcType=VARCHAR}");
        sql.SET("currency_code = #{record.currencyCode,jdbcType=VARCHAR}");
        sql.SET("market_cap = #{record.marketCap,jdbcType=VARCHAR}");
        sql.SET("price = #{record.price,jdbcType=VARCHAR}");
        sql.SET("turnover = #{record.turnover,jdbcType=VARCHAR}");
        sql.SET("volume = #{record.volume,jdbcType=VARCHAR}");
        sql.SET("changepercent = #{record.changepercent,jdbcType=VARCHAR}");
        sql.SET("k_line = #{record.kLine,jdbcType=VARCHAR}");
        sql.SET("crawl_status = #{record.crawlStatus,jdbcType=VARCHAR}");
        sql.SET("batch = #{record.batch,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        
        MarketCurrencyInfoCriteria example = (MarketCurrencyInfoCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_currency_info
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(MarketCurrencyInfo record) {
        SQL sql = new SQL();
        sql.UPDATE("market_currency_info");
        
        if (record.getCoinName() != null) {
            sql.SET("coin_name = #{coinName,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinImg() != null) {
            sql.SET("coin_img = #{coinImg,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrencyCode() != null) {
            sql.SET("currency_code = #{currencyCode,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketCap() != null) {
            sql.SET("market_cap = #{marketCap,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{price,jdbcType=VARCHAR}");
        }
        
        if (record.getTurnover() != null) {
            sql.SET("turnover = #{turnover,jdbcType=VARCHAR}");
        }
        
        if (record.getVolume() != null) {
            sql.SET("volume = #{volume,jdbcType=VARCHAR}");
        }
        
        if (record.getChangepercent() != null) {
            sql.SET("changepercent = #{changepercent,jdbcType=VARCHAR}");
        }
        
        if (record.getkLine() != null) {
            sql.SET("k_line = #{kLine,jdbcType=VARCHAR}");
        }
        
        if (record.getCrawlStatus() != null) {
            sql.SET("crawl_status = #{crawlStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getBatch() != null) {
            sql.SET("batch = #{batch,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_currency_info
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, MarketCurrencyInfoCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}