package com.blockchain.commune.mapper;

import com.blockchain.commune.model.MarketExchange;
import com.blockchain.commune.model.MarketExchangeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MarketExchangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange
     *
     * @mbg.generated
     */
    @SelectProvider(type=MarketExchangeSqlProvider.class, method="countByExample")
    long countByExample(MarketExchangeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange
     *
     * @mbg.generated
     */
    @DeleteProvider(type=MarketExchangeSqlProvider.class, method="deleteByExample")
    int deleteByExample(MarketExchangeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange
     *
     * @mbg.generated
     */
    @Delete({
        "delete from market_exchange",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange
     *
     * @mbg.generated
     */
    @Insert({
        "insert into market_exchange (id, market_id, ",
        "name, alias, website, ",
        "language, logo, ",
        "create_time)",
        "values (#{id,jdbcType=VARCHAR}, #{marketId,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{alias,jdbcType=VARCHAR}, #{website,jdbcType=VARCHAR}, ",
        "#{language,jdbcType=VARCHAR}, #{logo,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(MarketExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange
     *
     * @mbg.generated
     */
    @InsertProvider(type=MarketExchangeSqlProvider.class, method="insertSelective")
    int insertSelective(MarketExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange
     *
     * @mbg.generated
     */
    @SelectProvider(type=MarketExchangeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="market_id", property="marketId", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="alias", property="alias", jdbcType=JdbcType.VARCHAR),
        @Result(column="website", property="website", jdbcType=JdbcType.VARCHAR),
        @Result(column="language", property="language", jdbcType=JdbcType.VARCHAR),
        @Result(column="logo", property="logo", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<MarketExchange> selectByExample(MarketExchangeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, market_id, name, alias, website, language, logo, create_time",
        "from market_exchange",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="market_id", property="marketId", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="alias", property="alias", jdbcType=JdbcType.VARCHAR),
        @Result(column="website", property="website", jdbcType=JdbcType.VARCHAR),
        @Result(column="language", property="language", jdbcType=JdbcType.VARCHAR),
        @Result(column="logo", property="logo", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    MarketExchange selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketExchangeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MarketExchange record, @Param("example") MarketExchangeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketExchangeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MarketExchange record, @Param("example") MarketExchangeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketExchangeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MarketExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_exchange
     *
     * @mbg.generated
     */
    @Update({
        "update market_exchange",
        "set market_id = #{marketId,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "alias = #{alias,jdbcType=VARCHAR},",
          "website = #{website,jdbcType=VARCHAR},",
          "language = #{language,jdbcType=VARCHAR},",
          "logo = #{logo,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(MarketExchange record);
}