package com.blockchain.commune.mapper;

import com.blockchain.commune.model.MarketCap;
import com.blockchain.commune.model.MarketCapCriteria.Criteria;
import com.blockchain.commune.model.MarketCapCriteria.Criterion;
import com.blockchain.commune.model.MarketCapCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class MarketCapSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    public String countByExample(MarketCapCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("market_cap");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    public String deleteByExample(MarketCapCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("market_cap");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    public String insertSelective(MarketCap record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("market_cap");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbol() != null) {
            sql.VALUES("symbol", "#{symbol,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.VALUES("price", "#{price,jdbcType=DECIMAL}");
        }
        
        if (record.getPriceUsd() != null) {
            sql.VALUES("price_usd", "#{priceUsd,jdbcType=DECIMAL}");
        }
        
        if (record.getMarketCapDisplayCny() != null) {
            sql.VALUES("market_cap_display_cny", "#{marketCapDisplayCny,jdbcType=DECIMAL}");
        }
        
        if (record.getVolume24h() != null) {
            sql.VALUES("volume_24h", "#{volume24h,jdbcType=DECIMAL}");
        }
        
        if (record.getLogo() != null) {
            sql.VALUES("logo", "#{logo,jdbcType=VARCHAR}");
        }
        
        if (record.getAlias() != null) {
            sql.VALUES("alias", "#{alias,jdbcType=VARCHAR}");
        }
        
        if (record.getRank() != null) {
            sql.VALUES("rank", "#{rank,jdbcType=INTEGER}");
        }
        
        if (record.getPercentChangeDisplay() != null) {
            sql.VALUES("percent_change_display", "#{percentChangeDisplay,jdbcType=DECIMAL}");
        }
        
        if (record.getVolume24hUsd() != null) {
            sql.VALUES("volume_24h_usd", "#{volume24hUsd,jdbcType=DECIMAL}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getBatch() != null) {
            sql.VALUES("batch", "#{batch,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    public String selectByExample(MarketCapCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("symbol");
        sql.SELECT("price");
        sql.SELECT("price_usd");
        sql.SELECT("market_cap_display_cny");
        sql.SELECT("volume_24h");
        sql.SELECT("logo");
        sql.SELECT("alias");
        sql.SELECT("rank");
        sql.SELECT("percent_change_display");
        sql.SELECT("volume_24h_usd");
        sql.SELECT("create_time");
        sql.SELECT("batch");
        sql.SELECT("name");
        sql.FROM("market_cap");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MarketCap record = (MarketCap) parameter.get("record");
        MarketCapCriteria example = (MarketCapCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("market_cap");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbol() != null) {
            sql.SET("symbol = #{record.symbol,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{record.price,jdbcType=DECIMAL}");
        }
        
        if (record.getPriceUsd() != null) {
            sql.SET("price_usd = #{record.priceUsd,jdbcType=DECIMAL}");
        }
        
        if (record.getMarketCapDisplayCny() != null) {
            sql.SET("market_cap_display_cny = #{record.marketCapDisplayCny,jdbcType=DECIMAL}");
        }
        
        if (record.getVolume24h() != null) {
            sql.SET("volume_24h = #{record.volume24h,jdbcType=DECIMAL}");
        }
        
        if (record.getLogo() != null) {
            sql.SET("logo = #{record.logo,jdbcType=VARCHAR}");
        }
        
        if (record.getAlias() != null) {
            sql.SET("alias = #{record.alias,jdbcType=VARCHAR}");
        }
        
        if (record.getRank() != null) {
            sql.SET("rank = #{record.rank,jdbcType=INTEGER}");
        }
        
        if (record.getPercentChangeDisplay() != null) {
            sql.SET("percent_change_display = #{record.percentChangeDisplay,jdbcType=DECIMAL}");
        }
        
        if (record.getVolume24hUsd() != null) {
            sql.SET("volume_24h_usd = #{record.volume24hUsd,jdbcType=DECIMAL}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getBatch() != null) {
            sql.SET("batch = #{record.batch,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("market_cap");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("symbol = #{record.symbol,jdbcType=VARCHAR}");
        sql.SET("price = #{record.price,jdbcType=DECIMAL}");
        sql.SET("price_usd = #{record.priceUsd,jdbcType=DECIMAL}");
        sql.SET("market_cap_display_cny = #{record.marketCapDisplayCny,jdbcType=DECIMAL}");
        sql.SET("volume_24h = #{record.volume24h,jdbcType=DECIMAL}");
        sql.SET("logo = #{record.logo,jdbcType=VARCHAR}");
        sql.SET("alias = #{record.alias,jdbcType=VARCHAR}");
        sql.SET("rank = #{record.rank,jdbcType=INTEGER}");
        sql.SET("percent_change_display = #{record.percentChangeDisplay,jdbcType=DECIMAL}");
        sql.SET("volume_24h_usd = #{record.volume24hUsd,jdbcType=DECIMAL}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("batch = #{record.batch,jdbcType=VARCHAR}");
        sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        
        MarketCapCriteria example = (MarketCapCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(MarketCap record) {
        SQL sql = new SQL();
        sql.UPDATE("market_cap");
        
        if (record.getSymbol() != null) {
            sql.SET("symbol = #{symbol,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{price,jdbcType=DECIMAL}");
        }
        
        if (record.getPriceUsd() != null) {
            sql.SET("price_usd = #{priceUsd,jdbcType=DECIMAL}");
        }
        
        if (record.getMarketCapDisplayCny() != null) {
            sql.SET("market_cap_display_cny = #{marketCapDisplayCny,jdbcType=DECIMAL}");
        }
        
        if (record.getVolume24h() != null) {
            sql.SET("volume_24h = #{volume24h,jdbcType=DECIMAL}");
        }
        
        if (record.getLogo() != null) {
            sql.SET("logo = #{logo,jdbcType=VARCHAR}");
        }
        
        if (record.getAlias() != null) {
            sql.SET("alias = #{alias,jdbcType=VARCHAR}");
        }
        
        if (record.getRank() != null) {
            sql.SET("rank = #{rank,jdbcType=INTEGER}");
        }
        
        if (record.getPercentChangeDisplay() != null) {
            sql.SET("percent_change_display = #{percentChangeDisplay,jdbcType=DECIMAL}");
        }
        
        if (record.getVolume24hUsd() != null) {
            sql.SET("volume_24h_usd = #{volume24hUsd,jdbcType=DECIMAL}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getBatch() != null) {
            sql.SET("batch = #{batch,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, MarketCapCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}