package com.blockchain.commune.mapper;

import com.blockchain.commune.model.MarketCap;
import com.blockchain.commune.model.MarketCapCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MarketCapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    @SelectProvider(type=MarketCapSqlProvider.class, method="countByExample")
    long countByExample(MarketCapCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    @DeleteProvider(type=MarketCapSqlProvider.class, method="deleteByExample")
    int deleteByExample(MarketCapCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    @Delete({
        "delete from market_cap",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    @Insert({
        "insert into market_cap (id, symbol, ",
        "price, price_usd, ",
        "market_cap_display_cny, volume_24h, ",
        "logo, alias, rank, ",
        "percent_change_display, volume_24h_usd, ",
        "create_time, batch, ",
        "name)",
        "values (#{id,jdbcType=VARCHAR}, #{symbol,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{priceUsd,jdbcType=DECIMAL}, ",
        "#{marketCapDisplayCny,jdbcType=DECIMAL}, #{volume24h,jdbcType=DECIMAL}, ",
        "#{logo,jdbcType=VARCHAR}, #{alias,jdbcType=VARCHAR}, #{rank,jdbcType=INTEGER}, ",
        "#{percentChangeDisplay,jdbcType=DECIMAL}, #{volume24hUsd,jdbcType=DECIMAL}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{batch,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR})"
    })
    int insert(MarketCap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    @InsertProvider(type=MarketCapSqlProvider.class, method="insertSelective")
    int insertSelective(MarketCap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    @SelectProvider(type=MarketCapSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="symbol", property="symbol", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="price_usd", property="priceUsd", jdbcType=JdbcType.DECIMAL),
        @Result(column="market_cap_display_cny", property="marketCapDisplayCny", jdbcType=JdbcType.DECIMAL),
        @Result(column="volume_24h", property="volume24h", jdbcType=JdbcType.DECIMAL),
        @Result(column="logo", property="logo", jdbcType=JdbcType.VARCHAR),
        @Result(column="alias", property="alias", jdbcType=JdbcType.VARCHAR),
        @Result(column="rank", property="rank", jdbcType=JdbcType.INTEGER),
        @Result(column="percent_change_display", property="percentChangeDisplay", jdbcType=JdbcType.DECIMAL),
        @Result(column="volume_24h_usd", property="volume24hUsd", jdbcType=JdbcType.DECIMAL),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="batch", property="batch", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR)
    })
    List<MarketCap> selectByExample(MarketCapCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, symbol, price, price_usd, market_cap_display_cny, volume_24h, logo, alias, ",
        "rank, percent_change_display, volume_24h_usd, create_time, batch, name",
        "from market_cap",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="symbol", property="symbol", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="price_usd", property="priceUsd", jdbcType=JdbcType.DECIMAL),
        @Result(column="market_cap_display_cny", property="marketCapDisplayCny", jdbcType=JdbcType.DECIMAL),
        @Result(column="volume_24h", property="volume24h", jdbcType=JdbcType.DECIMAL),
        @Result(column="logo", property="logo", jdbcType=JdbcType.VARCHAR),
        @Result(column="alias", property="alias", jdbcType=JdbcType.VARCHAR),
        @Result(column="rank", property="rank", jdbcType=JdbcType.INTEGER),
        @Result(column="percent_change_display", property="percentChangeDisplay", jdbcType=JdbcType.DECIMAL),
        @Result(column="volume_24h_usd", property="volume24hUsd", jdbcType=JdbcType.DECIMAL),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="batch", property="batch", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR)
    })
    MarketCap selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketCapSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MarketCap record, @Param("example") MarketCapCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketCapSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MarketCap record, @Param("example") MarketCapCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketCapSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MarketCap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_cap
     *
     * @mbg.generated
     */
    @Update({
        "update market_cap",
        "set symbol = #{symbol,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "price_usd = #{priceUsd,jdbcType=DECIMAL},",
          "market_cap_display_cny = #{marketCapDisplayCny,jdbcType=DECIMAL},",
          "volume_24h = #{volume24h,jdbcType=DECIMAL},",
          "logo = #{logo,jdbcType=VARCHAR},",
          "alias = #{alias,jdbcType=VARCHAR},",
          "rank = #{rank,jdbcType=INTEGER},",
          "percent_change_display = #{percentChangeDisplay,jdbcType=DECIMAL},",
          "volume_24h_usd = #{volume24hUsd,jdbcType=DECIMAL},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "batch = #{batch,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(MarketCap record);
}