package com.blockchain.commune.mapper;

import com.blockchain.commune.model.NewsDetail;
import com.blockchain.commune.model.NewsDetailCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface NewsDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated
     */
    @SelectProvider(type=NewsDetailSqlProvider.class, method="countByExample")
    long countByExample(NewsDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated
     */
    @DeleteProvider(type=NewsDetailSqlProvider.class, method="deleteByExample")
    int deleteByExample(NewsDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated
     */
    @Delete({
        "delete from news_detail",
        "where news_id = #{newsId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated
     */
    @Insert({
        "insert into news_detail (news_id, package_detail, ",
        "create_time, update_time, ",
        "detail)",
        "values (#{newsId,jdbcType=VARCHAR}, #{packageDetail,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{detail,jdbcType=LONGVARCHAR})"
    })
    int insert(NewsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated
     */
    @InsertProvider(type=NewsDetailSqlProvider.class, method="insertSelective")
    int insertSelective(NewsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated
     */
    @SelectProvider(type=NewsDetailSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="news_id", property="newsId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="package_detail", property="packageDetail", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="detail", property="detail", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<NewsDetail> selectByExampleWithBLOBs(NewsDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated
     */
    @SelectProvider(type=NewsDetailSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="news_id", property="newsId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="package_detail", property="packageDetail", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<NewsDetail> selectByExample(NewsDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "news_id, package_detail, create_time, update_time, detail",
        "from news_detail",
        "where news_id = #{newsId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="news_id", property="newsId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="package_detail", property="packageDetail", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="detail", property="detail", jdbcType=JdbcType.LONGVARCHAR)
    })
    NewsDetail selectByPrimaryKey(String newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated
     */
    @UpdateProvider(type=NewsDetailSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") NewsDetail record, @Param("example") NewsDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated
     */
    @UpdateProvider(type=NewsDetailSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") NewsDetail record, @Param("example") NewsDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated
     */
    @UpdateProvider(type=NewsDetailSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") NewsDetail record, @Param("example") NewsDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated
     */
    @UpdateProvider(type=NewsDetailSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(NewsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated
     */
    @Update({
        "update news_detail",
        "set package_detail = #{packageDetail,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "detail = #{detail,jdbcType=LONGVARCHAR}",
        "where news_id = #{newsId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(NewsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated
     */
    @Update({
        "update news_detail",
        "set package_detail = #{packageDetail,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where news_id = #{newsId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(NewsDetail record);
}