package com.blockchain.commune.mapper;

import com.blockchain.commune.model.News;
import com.blockchain.commune.model.NewsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    @SelectProvider(type=NewsSqlProvider.class, method="countByExample")
    long countByExample(NewsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    @DeleteProvider(type=NewsSqlProvider.class, method="deleteByExample")
    int deleteByExample(NewsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    @Delete({
        "delete from news",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    @Insert({
        "insert into news (id, cat_id, ",
        "title, content, ",
        "excerpt, online_status, ",
        "collect_num, news_img, ",
        "author, editor, ",
        "unique_mark, create_time, ",
        "update_time, click, ",
        "sort)",
        "values (#{id,jdbcType=VARCHAR}, #{catId,jdbcType=VARCHAR}, ",
        "#{title,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{excerpt,jdbcType=VARCHAR}, #{onlineStatus,jdbcType=TINYINT}, ",
        "#{collectNum,jdbcType=INTEGER}, #{newsImg,jdbcType=VARCHAR}, ",
        "#{author,jdbcType=VARCHAR}, #{editor,jdbcType=VARCHAR}, ",
        "#{uniqueMark,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{click,jdbcType=TINYINT}, ",
        "#{sort,jdbcType=INTEGER})"
    })
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    @InsertProvider(type=NewsSqlProvider.class, method="insertSelective")
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    @SelectProvider(type=NewsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="cat_id", property="catId", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="excerpt", property="excerpt", jdbcType=JdbcType.VARCHAR),
        @Result(column="online_status", property="onlineStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="collect_num", property="collectNum", jdbcType=JdbcType.INTEGER),
        @Result(column="news_img", property="newsImg", jdbcType=JdbcType.VARCHAR),
        @Result(column="author", property="author", jdbcType=JdbcType.VARCHAR),
        @Result(column="editor", property="editor", jdbcType=JdbcType.VARCHAR),
        @Result(column="unique_mark", property="uniqueMark", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="click", property="click", jdbcType=JdbcType.TINYINT),
        @Result(column="sort", property="sort", jdbcType=JdbcType.INTEGER)
    })
    List<News> selectByExample(NewsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, cat_id, title, content, excerpt, online_status, collect_num, news_img, author, ",
        "editor, unique_mark, create_time, update_time, click, sort",
        "from news",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="cat_id", property="catId", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="excerpt", property="excerpt", jdbcType=JdbcType.VARCHAR),
        @Result(column="online_status", property="onlineStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="collect_num", property="collectNum", jdbcType=JdbcType.INTEGER),
        @Result(column="news_img", property="newsImg", jdbcType=JdbcType.VARCHAR),
        @Result(column="author", property="author", jdbcType=JdbcType.VARCHAR),
        @Result(column="editor", property="editor", jdbcType=JdbcType.VARCHAR),
        @Result(column="unique_mark", property="uniqueMark", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="click", property="click", jdbcType=JdbcType.TINYINT),
        @Result(column="sort", property="sort", jdbcType=JdbcType.INTEGER)
    })
    News selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    @UpdateProvider(type=NewsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") News record, @Param("example") NewsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    @UpdateProvider(type=NewsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") News record, @Param("example") NewsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    @UpdateProvider(type=NewsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    @Update({
        "update news",
        "set cat_id = #{catId,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "excerpt = #{excerpt,jdbcType=VARCHAR},",
          "online_status = #{onlineStatus,jdbcType=TINYINT},",
          "collect_num = #{collectNum,jdbcType=INTEGER},",
          "news_img = #{newsImg,jdbcType=VARCHAR},",
          "author = #{author,jdbcType=VARCHAR},",
          "editor = #{editor,jdbcType=VARCHAR},",
          "unique_mark = #{uniqueMark,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "click = #{click,jdbcType=TINYINT},",
          "sort = #{sort,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(News record);
}