package com.blockchain.commune.mapper;

import com.blockchain.commune.model.News;
import com.blockchain.commune.model.NewsCriteria.Criteria;
import com.blockchain.commune.model.NewsCriteria.Criterion;
import com.blockchain.commune.model.NewsCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class NewsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public String countByExample(NewsCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("news");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public String deleteByExample(NewsCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("news");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public String insertSelective(News record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("news");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getCatId() != null) {
            sql.VALUES("cat_id", "#{catId,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            sql.VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            sql.VALUES("content", "#{content,jdbcType=VARCHAR}");
        }
        
        if (record.getExcerpt() != null) {
            sql.VALUES("excerpt", "#{excerpt,jdbcType=VARCHAR}");
        }
        
        if (record.getOnlineStatus() != null) {
            sql.VALUES("online_status", "#{onlineStatus,jdbcType=TINYINT}");
        }
        
        if (record.getCollectNum() != null) {
            sql.VALUES("collect_num", "#{collectNum,jdbcType=INTEGER}");
        }
        
        if (record.getNewsImg() != null) {
            sql.VALUES("news_img", "#{newsImg,jdbcType=VARCHAR}");
        }
        
        if (record.getAuthor() != null) {
            sql.VALUES("author", "#{author,jdbcType=VARCHAR}");
        }
        
        if (record.getEditor() != null) {
            sql.VALUES("editor", "#{editor,jdbcType=VARCHAR}");
        }
        
        if (record.getUniqueMark() != null) {
            sql.VALUES("unique_mark", "#{uniqueMark,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getClick() != null) {
            sql.VALUES("click", "#{click,jdbcType=TINYINT}");
        }
        
        if (record.getSort() != null) {
            sql.VALUES("sort", "#{sort,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public String selectByExample(NewsCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("cat_id");
        sql.SELECT("title");
        sql.SELECT("content");
        sql.SELECT("excerpt");
        sql.SELECT("online_status");
        sql.SELECT("collect_num");
        sql.SELECT("news_img");
        sql.SELECT("author");
        sql.SELECT("editor");
        sql.SELECT("unique_mark");
        sql.SELECT("create_time");
        sql.SELECT("update_time");
        sql.SELECT("click");
        sql.SELECT("sort");
        sql.FROM("news");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        News record = (News) parameter.get("record");
        NewsCriteria example = (NewsCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("news");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getCatId() != null) {
            sql.SET("cat_id = #{record.catId,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("title = #{record.title,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            sql.SET("content = #{record.content,jdbcType=VARCHAR}");
        }
        
        if (record.getExcerpt() != null) {
            sql.SET("excerpt = #{record.excerpt,jdbcType=VARCHAR}");
        }
        
        if (record.getOnlineStatus() != null) {
            sql.SET("online_status = #{record.onlineStatus,jdbcType=TINYINT}");
        }
        
        if (record.getCollectNum() != null) {
            sql.SET("collect_num = #{record.collectNum,jdbcType=INTEGER}");
        }
        
        if (record.getNewsImg() != null) {
            sql.SET("news_img = #{record.newsImg,jdbcType=VARCHAR}");
        }
        
        if (record.getAuthor() != null) {
            sql.SET("author = #{record.author,jdbcType=VARCHAR}");
        }
        
        if (record.getEditor() != null) {
            sql.SET("editor = #{record.editor,jdbcType=VARCHAR}");
        }
        
        if (record.getUniqueMark() != null) {
            sql.SET("unique_mark = #{record.uniqueMark,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getClick() != null) {
            sql.SET("click = #{record.click,jdbcType=TINYINT}");
        }
        
        if (record.getSort() != null) {
            sql.SET("sort = #{record.sort,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("news");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("cat_id = #{record.catId,jdbcType=VARCHAR}");
        sql.SET("title = #{record.title,jdbcType=VARCHAR}");
        sql.SET("content = #{record.content,jdbcType=VARCHAR}");
        sql.SET("excerpt = #{record.excerpt,jdbcType=VARCHAR}");
        sql.SET("online_status = #{record.onlineStatus,jdbcType=TINYINT}");
        sql.SET("collect_num = #{record.collectNum,jdbcType=INTEGER}");
        sql.SET("news_img = #{record.newsImg,jdbcType=VARCHAR}");
        sql.SET("author = #{record.author,jdbcType=VARCHAR}");
        sql.SET("editor = #{record.editor,jdbcType=VARCHAR}");
        sql.SET("unique_mark = #{record.uniqueMark,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        sql.SET("click = #{record.click,jdbcType=TINYINT}");
        sql.SET("sort = #{record.sort,jdbcType=INTEGER}");
        
        NewsCriteria example = (NewsCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(News record) {
        SQL sql = new SQL();
        sql.UPDATE("news");
        
        if (record.getCatId() != null) {
            sql.SET("cat_id = #{catId,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            sql.SET("content = #{content,jdbcType=VARCHAR}");
        }
        
        if (record.getExcerpt() != null) {
            sql.SET("excerpt = #{excerpt,jdbcType=VARCHAR}");
        }
        
        if (record.getOnlineStatus() != null) {
            sql.SET("online_status = #{onlineStatus,jdbcType=TINYINT}");
        }
        
        if (record.getCollectNum() != null) {
            sql.SET("collect_num = #{collectNum,jdbcType=INTEGER}");
        }
        
        if (record.getNewsImg() != null) {
            sql.SET("news_img = #{newsImg,jdbcType=VARCHAR}");
        }
        
        if (record.getAuthor() != null) {
            sql.SET("author = #{author,jdbcType=VARCHAR}");
        }
        
        if (record.getEditor() != null) {
            sql.SET("editor = #{editor,jdbcType=VARCHAR}");
        }
        
        if (record.getUniqueMark() != null) {
            sql.SET("unique_mark = #{uniqueMark,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getClick() != null) {
            sql.SET("click = #{click,jdbcType=TINYINT}");
        }
        
        if (record.getSort() != null) {
            sql.SET("sort = #{sort,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, NewsCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}