package com.blockchain.commune.mapper;

import com.blockchain.commune.model.PurseSubAccount;
import com.blockchain.commune.model.PurseSubAccountCriteria.Criteria;
import com.blockchain.commune.model.PurseSubAccountCriteria.Criterion;
import com.blockchain.commune.model.PurseSubAccountCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class PurseSubAccountSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_sub_account
     *
     * @mbg.generated
     */
    public String countByExample(PurseSubAccountCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("purse_sub_account");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_sub_account
     *
     * @mbg.generated
     */
    public String deleteByExample(PurseSubAccountCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("purse_sub_account");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_sub_account
     *
     * @mbg.generated
     */
    public String insertSelective(PurseSubAccount record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("purse_sub_account");
        
        if (record.getSubAccountId() != null) {
            sql.VALUES("sub_account_id", "#{subAccountId,jdbcType=VARCHAR}");
        }
        
        if (record.getAccountId() != null) {
            sql.VALUES("account_id", "#{accountId,jdbcType=VARCHAR}");
        }
        
        if (record.getSubAccountType() != null) {
            sql.VALUES("sub_account_type", "#{subAccountType,jdbcType=VARCHAR}");
        }
        
        if (record.getPurseAddress() != null) {
            sql.VALUES("purse_address", "#{purseAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getPurseAddressQrcode() != null) {
            sql.VALUES("purse_address_qrcode", "#{purseAddressQrcode,jdbcType=VARCHAR}");
        }
        
        if (record.getTotalAivilable() != null) {
            sql.VALUES("total_aivilable", "#{totalAivilable,jdbcType=DECIMAL}");
        }
        
        if (record.getAvailableAivilable() != null) {
            sql.VALUES("available_aivilable", "#{availableAivilable,jdbcType=DECIMAL}");
        }
        
        if (record.getBlockAivilable() != null) {
            sql.VALUES("block_aivilable", "#{blockAivilable,jdbcType=DECIMAL}");
        }
        
        if (record.getSubAccountStatus() != null) {
            sql.VALUES("sub_account_status", "#{subAccountStatus,jdbcType=TINYINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_sub_account
     *
     * @mbg.generated
     */
    public String selectByExample(PurseSubAccountCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("sub_account_id");
        } else {
            sql.SELECT("sub_account_id");
        }
        sql.SELECT("account_id");
        sql.SELECT("sub_account_type");
        sql.SELECT("purse_address");
        sql.SELECT("purse_address_qrcode");
        sql.SELECT("total_aivilable");
        sql.SELECT("available_aivilable");
        sql.SELECT("block_aivilable");
        sql.SELECT("sub_account_status");
        sql.SELECT("create_time");
        sql.SELECT("update_time");
        sql.FROM("purse_sub_account");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_sub_account
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        PurseSubAccount record = (PurseSubAccount) parameter.get("record");
        PurseSubAccountCriteria example = (PurseSubAccountCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("purse_sub_account");
        
        if (record.getSubAccountId() != null) {
            sql.SET("sub_account_id = #{record.subAccountId,jdbcType=VARCHAR}");
        }
        
        if (record.getAccountId() != null) {
            sql.SET("account_id = #{record.accountId,jdbcType=VARCHAR}");
        }
        
        if (record.getSubAccountType() != null) {
            sql.SET("sub_account_type = #{record.subAccountType,jdbcType=VARCHAR}");
        }
        
        if (record.getPurseAddress() != null) {
            sql.SET("purse_address = #{record.purseAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getPurseAddressQrcode() != null) {
            sql.SET("purse_address_qrcode = #{record.purseAddressQrcode,jdbcType=VARCHAR}");
        }
        
        if (record.getTotalAivilable() != null) {
            sql.SET("total_aivilable = #{record.totalAivilable,jdbcType=DECIMAL}");
        }
        
        if (record.getAvailableAivilable() != null) {
            sql.SET("available_aivilable = #{record.availableAivilable,jdbcType=DECIMAL}");
        }
        
        if (record.getBlockAivilable() != null) {
            sql.SET("block_aivilable = #{record.blockAivilable,jdbcType=DECIMAL}");
        }
        
        if (record.getSubAccountStatus() != null) {
            sql.SET("sub_account_status = #{record.subAccountStatus,jdbcType=TINYINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_sub_account
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("purse_sub_account");
        
        sql.SET("sub_account_id = #{record.subAccountId,jdbcType=VARCHAR}");
        sql.SET("account_id = #{record.accountId,jdbcType=VARCHAR}");
        sql.SET("sub_account_type = #{record.subAccountType,jdbcType=VARCHAR}");
        sql.SET("purse_address = #{record.purseAddress,jdbcType=VARCHAR}");
        sql.SET("purse_address_qrcode = #{record.purseAddressQrcode,jdbcType=VARCHAR}");
        sql.SET("total_aivilable = #{record.totalAivilable,jdbcType=DECIMAL}");
        sql.SET("available_aivilable = #{record.availableAivilable,jdbcType=DECIMAL}");
        sql.SET("block_aivilable = #{record.blockAivilable,jdbcType=DECIMAL}");
        sql.SET("sub_account_status = #{record.subAccountStatus,jdbcType=TINYINT}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        
        PurseSubAccountCriteria example = (PurseSubAccountCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_sub_account
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(PurseSubAccount record) {
        SQL sql = new SQL();
        sql.UPDATE("purse_sub_account");
        
        if (record.getAccountId() != null) {
            sql.SET("account_id = #{accountId,jdbcType=VARCHAR}");
        }
        
        if (record.getSubAccountType() != null) {
            sql.SET("sub_account_type = #{subAccountType,jdbcType=VARCHAR}");
        }
        
        if (record.getPurseAddress() != null) {
            sql.SET("purse_address = #{purseAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getPurseAddressQrcode() != null) {
            sql.SET("purse_address_qrcode = #{purseAddressQrcode,jdbcType=VARCHAR}");
        }
        
        if (record.getTotalAivilable() != null) {
            sql.SET("total_aivilable = #{totalAivilable,jdbcType=DECIMAL}");
        }
        
        if (record.getAvailableAivilable() != null) {
            sql.SET("available_aivilable = #{availableAivilable,jdbcType=DECIMAL}");
        }
        
        if (record.getBlockAivilable() != null) {
            sql.SET("block_aivilable = #{blockAivilable,jdbcType=DECIMAL}");
        }
        
        if (record.getSubAccountStatus() != null) {
            sql.SET("sub_account_status = #{subAccountStatus,jdbcType=TINYINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("sub_account_id = #{subAccountId,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purse_sub_account
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, PurseSubAccountCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}