package com.blockchain.commune.mapper;

import com.blockchain.commune.model.ScrollItem;
import com.blockchain.commune.model.ScrollItemCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ScrollItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scroll_item
     *
     * @mbg.generated
     */
    @SelectProvider(type=ScrollItemSqlProvider.class, method="countByExample")
    long countByExample(ScrollItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scroll_item
     *
     * @mbg.generated
     */
    @DeleteProvider(type=ScrollItemSqlProvider.class, method="deleteByExample")
    int deleteByExample(ScrollItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scroll_item
     *
     * @mbg.generated
     */
    @Delete({
        "delete from scroll_item",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scroll_item
     *
     * @mbg.generated
     */
    @Insert({
        "insert into scroll_item (id, item_name, ",
        "item_img_url, action_type, ",
        "action_value, sort, ",
        "create_time, action_value_title, ",
        "attach)",
        "values (#{id,jdbcType=VARCHAR}, #{itemName,jdbcType=VARCHAR}, ",
        "#{itemImgUrl,jdbcType=VARCHAR}, #{actionType,jdbcType=VARCHAR}, ",
        "#{actionValue,jdbcType=VARCHAR}, #{sort,jdbcType=BIGINT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{actionValueTitle,jdbcType=VARCHAR}, ",
        "#{attach,jdbcType=LONGVARCHAR})"
    })
    int insert(ScrollItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scroll_item
     *
     * @mbg.generated
     */
    @InsertProvider(type=ScrollItemSqlProvider.class, method="insertSelective")
    int insertSelective(ScrollItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scroll_item
     *
     * @mbg.generated
     */
    @SelectProvider(type=ScrollItemSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="item_name", property="itemName", jdbcType=JdbcType.VARCHAR),
        @Result(column="item_img_url", property="itemImgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="action_type", property="actionType", jdbcType=JdbcType.VARCHAR),
        @Result(column="action_value", property="actionValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort", property="sort", jdbcType=JdbcType.BIGINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="action_value_title", property="actionValueTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="attach", property="attach", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<ScrollItem> selectByExampleWithBLOBs(ScrollItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scroll_item
     *
     * @mbg.generated
     */
    @SelectProvider(type=ScrollItemSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="item_name", property="itemName", jdbcType=JdbcType.VARCHAR),
        @Result(column="item_img_url", property="itemImgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="action_type", property="actionType", jdbcType=JdbcType.VARCHAR),
        @Result(column="action_value", property="actionValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort", property="sort", jdbcType=JdbcType.BIGINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="action_value_title", property="actionValueTitle", jdbcType=JdbcType.VARCHAR)
    })
    List<ScrollItem> selectByExample(ScrollItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scroll_item
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, item_name, item_img_url, action_type, action_value, sort, create_time, action_value_title, ",
        "attach",
        "from scroll_item",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="item_name", property="itemName", jdbcType=JdbcType.VARCHAR),
        @Result(column="item_img_url", property="itemImgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="action_type", property="actionType", jdbcType=JdbcType.VARCHAR),
        @Result(column="action_value", property="actionValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort", property="sort", jdbcType=JdbcType.BIGINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="action_value_title", property="actionValueTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="attach", property="attach", jdbcType=JdbcType.LONGVARCHAR)
    })
    ScrollItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scroll_item
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ScrollItemSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ScrollItem record, @Param("example") ScrollItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scroll_item
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ScrollItemSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") ScrollItem record, @Param("example") ScrollItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scroll_item
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ScrollItemSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ScrollItem record, @Param("example") ScrollItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scroll_item
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ScrollItemSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ScrollItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scroll_item
     *
     * @mbg.generated
     */
    @Update({
        "update scroll_item",
        "set item_name = #{itemName,jdbcType=VARCHAR},",
          "item_img_url = #{itemImgUrl,jdbcType=VARCHAR},",
          "action_type = #{actionType,jdbcType=VARCHAR},",
          "action_value = #{actionValue,jdbcType=VARCHAR},",
          "sort = #{sort,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "action_value_title = #{actionValueTitle,jdbcType=VARCHAR},",
          "attach = #{attach,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(ScrollItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scroll_item
     *
     * @mbg.generated
     */
    @Update({
        "update scroll_item",
        "set item_name = #{itemName,jdbcType=VARCHAR},",
          "item_img_url = #{itemImgUrl,jdbcType=VARCHAR},",
          "action_type = #{actionType,jdbcType=VARCHAR},",
          "action_value = #{actionValue,jdbcType=VARCHAR},",
          "sort = #{sort,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "action_value_title = #{actionValueTitle,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ScrollItem record);
}