package com.blockchain.commune.mapper;

import com.blockchain.commune.model.SmsCode;
import com.blockchain.commune.model.SmsCodeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SmsCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    @SelectProvider(type=SmsCodeSqlProvider.class, method="countByExample")
    long countByExample(SmsCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    @DeleteProvider(type=SmsCodeSqlProvider.class, method="deleteByExample")
    int deleteByExample(SmsCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    @Delete({
        "delete from sms_code",
        "where mobile = #{mobile,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String mobile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    @Insert({
        "insert into sms_code (mobile, sms_code, ",
        "type, create_time)",
        "values (#{mobile,jdbcType=VARCHAR}, #{smsCode,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(SmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    @InsertProvider(type=SmsCodeSqlProvider.class, method="insertSelective")
    int insertSelective(SmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    @SelectProvider(type=SmsCodeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="sms_code", property="smsCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<SmsCode> selectByExample(SmsCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "mobile, sms_code, type, create_time",
        "from sms_code",
        "where mobile = #{mobile,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="sms_code", property="smsCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    SmsCode selectByPrimaryKey(String mobile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SmsCodeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SmsCode record, @Param("example") SmsCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SmsCodeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SmsCode record, @Param("example") SmsCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SmsCodeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    @Update({
        "update sms_code",
        "set sms_code = #{smsCode,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where mobile = #{mobile,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SmsCode record);
}