package com.blockchain.commune.mapper;

import com.blockchain.commune.model.SystemArgs;
import com.blockchain.commune.model.SystemArgsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SystemArgsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_args
     *
     * @mbg.generated
     */
    @SelectProvider(type=SystemArgsSqlProvider.class, method="countByExample")
    long countByExample(SystemArgsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_args
     *
     * @mbg.generated
     */
    @DeleteProvider(type=SystemArgsSqlProvider.class, method="deleteByExample")
    int deleteByExample(SystemArgsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_args
     *
     * @mbg.generated
     */
    @Insert({
        "insert into system_args (sys_key, sys_value, ",
        "sys_desc)",
        "values (#{sysKey,jdbcType=VARCHAR}, #{sysValue,jdbcType=VARCHAR}, ",
        "#{sysDesc,jdbcType=VARCHAR})"
    })
    int insert(SystemArgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_args
     *
     * @mbg.generated
     */
    @InsertProvider(type=SystemArgsSqlProvider.class, method="insertSelective")
    int insertSelective(SystemArgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_args
     *
     * @mbg.generated
     */
    @SelectProvider(type=SystemArgsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="sys_key", property="sysKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="sys_value", property="sysValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="sys_desc", property="sysDesc", jdbcType=JdbcType.VARCHAR)
    })
    List<SystemArgs> selectByExample(SystemArgsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_args
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SystemArgsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SystemArgs record, @Param("example") SystemArgsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_args
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SystemArgsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SystemArgs record, @Param("example") SystemArgsCriteria example);
}