package com.blockchain.commune.mapper;

import com.blockchain.commune.model.SystemArgs;
import com.blockchain.commune.model.SystemArgsCriteria.Criteria;
import com.blockchain.commune.model.SystemArgsCriteria.Criterion;
import com.blockchain.commune.model.SystemArgsCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class SystemArgsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_args
     *
     * @mbg.generated
     */
    public String countByExample(SystemArgsCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("system_args");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_args
     *
     * @mbg.generated
     */
    public String deleteByExample(SystemArgsCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("system_args");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_args
     *
     * @mbg.generated
     */
    public String insertSelective(SystemArgs record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("system_args");
        
        if (record.getSysKey() != null) {
            sql.VALUES("sys_key", "#{sysKey,jdbcType=VARCHAR}");
        }
        
        if (record.getSysValue() != null) {
            sql.VALUES("sys_value", "#{sysValue,jdbcType=VARCHAR}");
        }
        
        if (record.getSysDesc() != null) {
            sql.VALUES("sys_desc", "#{sysDesc,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_args
     *
     * @mbg.generated
     */
    public String selectByExample(SystemArgsCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("sys_key");
        } else {
            sql.SELECT("sys_key");
        }
        sql.SELECT("sys_value");
        sql.SELECT("sys_desc");
        sql.FROM("system_args");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_args
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        SystemArgs record = (SystemArgs) parameter.get("record");
        SystemArgsCriteria example = (SystemArgsCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("system_args");
        
        if (record.getSysKey() != null) {
            sql.SET("sys_key = #{record.sysKey,jdbcType=VARCHAR}");
        }
        
        if (record.getSysValue() != null) {
            sql.SET("sys_value = #{record.sysValue,jdbcType=VARCHAR}");
        }
        
        if (record.getSysDesc() != null) {
            sql.SET("sys_desc = #{record.sysDesc,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_args
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("system_args");
        
        sql.SET("sys_key = #{record.sysKey,jdbcType=VARCHAR}");
        sql.SET("sys_value = #{record.sysValue,jdbcType=VARCHAR}");
        sql.SET("sys_desc = #{record.sysDesc,jdbcType=VARCHAR}");
        
        SystemArgsCriteria example = (SystemArgsCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_args
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, SystemArgsCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}