package com.blockchain.commune.mapper;

import com.blockchain.commune.model.TeamComputerCache;
import com.blockchain.commune.model.TeamComputerCacheCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TeamComputerCacheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_computer_cache
     *
     * @mbg.generated
     */
    @SelectProvider(type=TeamComputerCacheSqlProvider.class, method="countByExample")
    long countByExample(TeamComputerCacheCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_computer_cache
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TeamComputerCacheSqlProvider.class, method="deleteByExample")
    int deleteByExample(TeamComputerCacheCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_computer_cache
     *
     * @mbg.generated
     */
    @Delete({
        "delete from team_computer_cache",
        "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_computer_cache
     *
     * @mbg.generated
     */
    @Insert({
        "insert into team_computer_cache (user_id)",
        "values (#{userId,jdbcType=VARCHAR})"
    })
    int insert(TeamComputerCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_computer_cache
     *
     * @mbg.generated
     */
    @InsertProvider(type=TeamComputerCacheSqlProvider.class, method="insertSelective")
    int insertSelective(TeamComputerCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_computer_cache
     *
     * @mbg.generated
     */
    @SelectProvider(type=TeamComputerCacheSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR, id=true)
    })
    List<TeamComputerCache> selectByExample(TeamComputerCacheCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_computer_cache
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TeamComputerCacheSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TeamComputerCache record, @Param("example") TeamComputerCacheCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_computer_cache
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TeamComputerCacheSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TeamComputerCache record, @Param("example") TeamComputerCacheCriteria example);
}