package com.blockchain.commune.mapper;

import com.blockchain.commune.model.UserRecommendedCode;
import com.blockchain.commune.model.UserRecommendedCodeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserRecommendedCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recommended_code
     *
     * @mbg.generated
     */
    @SelectProvider(type=UserRecommendedCodeSqlProvider.class, method="countByExample")
    long countByExample(UserRecommendedCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recommended_code
     *
     * @mbg.generated
     */
    @DeleteProvider(type=UserRecommendedCodeSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserRecommendedCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recommended_code
     *
     * @mbg.generated
     */
    @Delete({
        "delete from user_recommended_code",
        "where recommended_code = #{recommendedCode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String recommendedCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recommended_code
     *
     * @mbg.generated
     */
    @Insert({
        "insert into user_recommended_code (recommended_code, user_id, ",
        "recommended_url, recommended_qrcode, ",
        "update_time, create_time)",
        "values (#{recommendedCode,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, ",
        "#{recommendedUrl,jdbcType=VARCHAR}, #{recommendedQrcode,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(UserRecommendedCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recommended_code
     *
     * @mbg.generated
     */
    @InsertProvider(type=UserRecommendedCodeSqlProvider.class, method="insertSelective")
    int insertSelective(UserRecommendedCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recommended_code
     *
     * @mbg.generated
     */
    @SelectProvider(type=UserRecommendedCodeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="recommended_code", property="recommendedCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="recommended_url", property="recommendedUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="recommended_qrcode", property="recommendedQrcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<UserRecommendedCode> selectByExample(UserRecommendedCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recommended_code
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "recommended_code, user_id, recommended_url, recommended_qrcode, update_time, ",
        "create_time",
        "from user_recommended_code",
        "where recommended_code = #{recommendedCode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="recommended_code", property="recommendedCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="recommended_url", property="recommendedUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="recommended_qrcode", property="recommendedQrcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    UserRecommendedCode selectByPrimaryKey(String recommendedCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recommended_code
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserRecommendedCodeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserRecommendedCode record, @Param("example") UserRecommendedCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recommended_code
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserRecommendedCodeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserRecommendedCode record, @Param("example") UserRecommendedCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recommended_code
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserRecommendedCodeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserRecommendedCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recommended_code
     *
     * @mbg.generated
     */
    @Update({
        "update user_recommended_code",
        "set user_id = #{userId,jdbcType=VARCHAR},",
          "recommended_url = #{recommendedUrl,jdbcType=VARCHAR},",
          "recommended_qrcode = #{recommendedQrcode,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where recommended_code = #{recommendedCode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(UserRecommendedCode record);
}