package com.blockchain.commune.mapper;

import com.blockchain.commune.model.UserAuth;
import com.blockchain.commune.model.UserAuthCriteria.Criteria;
import com.blockchain.commune.model.UserAuthCriteria.Criterion;
import com.blockchain.commune.model.UserAuthCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class UserAuthSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated
     */
    public String countByExample(UserAuthCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("user_auth");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated
     */
    public String deleteByExample(UserAuthCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("user_auth");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated
     */
    public String insertSelective(UserAuth record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("user_auth");
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getIdno() != null) {
            sql.VALUES("idNo", "#{idno,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            sql.VALUES("sex", "#{sex,jdbcType=CHAR}");
        }
        
        if (record.getBirthday() != null) {
            sql.VALUES("birthday", "#{birthday,jdbcType=VARCHAR}");
        }
        
        if (record.getArea() != null) {
            sql.VALUES("area", "#{area,jdbcType=VARCHAR}");
        }
        
        if (record.getProvince() != null) {
            sql.VALUES("province", "#{province,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            sql.VALUES("city", "#{city,jdbcType=VARCHAR}");
        }
        
        if (record.getPrefecture() != null) {
            sql.VALUES("prefecture", "#{prefecture,jdbcType=VARCHAR}");
        }
        
        if (record.getAddrcode() != null) {
            sql.VALUES("addrcode", "#{addrcode,jdbcType=VARCHAR}");
        }
        
        if (record.getLastcode() != null) {
            sql.VALUES("lastcode", "#{lastcode,jdbcType=VARCHAR}");
        }
        
        if (record.getFront() != null) {
            sql.VALUES("front", "#{front,jdbcType=VARCHAR}");
        }
        
        if (record.getBack() != null) {
            sql.VALUES("back", "#{back,jdbcType=VARCHAR}");
        }
        
        if (record.getUserPic() != null) {
            sql.VALUES("user_pic", "#{userPic,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated
     */
    public String selectByExample(UserAuthCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("user_id");
        } else {
            sql.SELECT("user_id");
        }
        sql.SELECT("name");
        sql.SELECT("idNo");
        sql.SELECT("sex");
        sql.SELECT("birthday");
        sql.SELECT("area");
        sql.SELECT("province");
        sql.SELECT("city");
        sql.SELECT("prefecture");
        sql.SELECT("addrcode");
        sql.SELECT("lastcode");
        sql.SELECT("front");
        sql.SELECT("back");
        sql.SELECT("user_pic");
        sql.SELECT("create_time");
        sql.SELECT("update_time");
        sql.FROM("user_auth");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        UserAuth record = (UserAuth) parameter.get("record");
        UserAuthCriteria example = (UserAuthCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("user_auth");
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        }
        
        if (record.getIdno() != null) {
            sql.SET("idNo = #{record.idno,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            sql.SET("sex = #{record.sex,jdbcType=CHAR}");
        }
        
        if (record.getBirthday() != null) {
            sql.SET("birthday = #{record.birthday,jdbcType=VARCHAR}");
        }
        
        if (record.getArea() != null) {
            sql.SET("area = #{record.area,jdbcType=VARCHAR}");
        }
        
        if (record.getProvince() != null) {
            sql.SET("province = #{record.province,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            sql.SET("city = #{record.city,jdbcType=VARCHAR}");
        }
        
        if (record.getPrefecture() != null) {
            sql.SET("prefecture = #{record.prefecture,jdbcType=VARCHAR}");
        }
        
        if (record.getAddrcode() != null) {
            sql.SET("addrcode = #{record.addrcode,jdbcType=VARCHAR}");
        }
        
        if (record.getLastcode() != null) {
            sql.SET("lastcode = #{record.lastcode,jdbcType=VARCHAR}");
        }
        
        if (record.getFront() != null) {
            sql.SET("front = #{record.front,jdbcType=VARCHAR}");
        }
        
        if (record.getBack() != null) {
            sql.SET("back = #{record.back,jdbcType=VARCHAR}");
        }
        
        if (record.getUserPic() != null) {
            sql.SET("user_pic = #{record.userPic,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("user_auth");
        
        sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        sql.SET("idNo = #{record.idno,jdbcType=VARCHAR}");
        sql.SET("sex = #{record.sex,jdbcType=CHAR}");
        sql.SET("birthday = #{record.birthday,jdbcType=VARCHAR}");
        sql.SET("area = #{record.area,jdbcType=VARCHAR}");
        sql.SET("province = #{record.province,jdbcType=VARCHAR}");
        sql.SET("city = #{record.city,jdbcType=VARCHAR}");
        sql.SET("prefecture = #{record.prefecture,jdbcType=VARCHAR}");
        sql.SET("addrcode = #{record.addrcode,jdbcType=VARCHAR}");
        sql.SET("lastcode = #{record.lastcode,jdbcType=VARCHAR}");
        sql.SET("front = #{record.front,jdbcType=VARCHAR}");
        sql.SET("back = #{record.back,jdbcType=VARCHAR}");
        sql.SET("user_pic = #{record.userPic,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        
        UserAuthCriteria example = (UserAuthCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(UserAuth record) {
        SQL sql = new SQL();
        sql.UPDATE("user_auth");
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getIdno() != null) {
            sql.SET("idNo = #{idno,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            sql.SET("sex = #{sex,jdbcType=CHAR}");
        }
        
        if (record.getBirthday() != null) {
            sql.SET("birthday = #{birthday,jdbcType=VARCHAR}");
        }
        
        if (record.getArea() != null) {
            sql.SET("area = #{area,jdbcType=VARCHAR}");
        }
        
        if (record.getProvince() != null) {
            sql.SET("province = #{province,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            sql.SET("city = #{city,jdbcType=VARCHAR}");
        }
        
        if (record.getPrefecture() != null) {
            sql.SET("prefecture = #{prefecture,jdbcType=VARCHAR}");
        }
        
        if (record.getAddrcode() != null) {
            sql.SET("addrcode = #{addrcode,jdbcType=VARCHAR}");
        }
        
        if (record.getLastcode() != null) {
            sql.SET("lastcode = #{lastcode,jdbcType=VARCHAR}");
        }
        
        if (record.getFront() != null) {
            sql.SET("front = #{front,jdbcType=VARCHAR}");
        }
        
        if (record.getBack() != null) {
            sql.SET("back = #{back,jdbcType=VARCHAR}");
        }
        
        if (record.getUserPic() != null) {
            sql.SET("user_pic = #{userPic,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("user_id = #{userId,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, UserAuthCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}