package com.blockchain.commune.mapper;

import com.blockchain.commune.model.WalletSubAccount;
import com.blockchain.commune.model.WalletSubAccountCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WalletSubAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account
     *
     * @mbg.generated
     */
    @SelectProvider(type=WalletSubAccountSqlProvider.class, method="countByExample")
    long countByExample(WalletSubAccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account
     *
     * @mbg.generated
     */
    @DeleteProvider(type=WalletSubAccountSqlProvider.class, method="deleteByExample")
    int deleteByExample(WalletSubAccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account
     *
     * @mbg.generated
     */
    @Delete({
        "delete from wallet_sub_account",
        "where sub_account_id = #{subAccountId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String subAccountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account
     *
     * @mbg.generated
     */
    @Insert({
        "insert into wallet_sub_account (sub_account_id, account_id, ",
        "sub_account_type, total_aivilable, ",
        "available_aivilable, block_aivilable, ",
        "sub_account_status, create_time, ",
        "update_time)",
        "values (#{subAccountId,jdbcType=VARCHAR}, #{accountId,jdbcType=VARCHAR}, ",
        "#{subAccountType,jdbcType=VARCHAR}, #{totalAivilable,jdbcType=DECIMAL}, ",
        "#{availableAivilable,jdbcType=DECIMAL}, #{blockAivilable,jdbcType=DECIMAL}, ",
        "#{subAccountStatus,jdbcType=TINYINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(WalletSubAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account
     *
     * @mbg.generated
     */
    @InsertProvider(type=WalletSubAccountSqlProvider.class, method="insertSelective")
    int insertSelective(WalletSubAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account
     *
     * @mbg.generated
     */
    @SelectProvider(type=WalletSubAccountSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="sub_account_id", property="subAccountId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="account_id", property="accountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sub_account_type", property="subAccountType", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_aivilable", property="totalAivilable", jdbcType=JdbcType.DECIMAL),
        @Result(column="available_aivilable", property="availableAivilable", jdbcType=JdbcType.DECIMAL),
        @Result(column="block_aivilable", property="blockAivilable", jdbcType=JdbcType.DECIMAL),
        @Result(column="sub_account_status", property="subAccountStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<WalletSubAccount> selectByExample(WalletSubAccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "sub_account_id, account_id, sub_account_type, total_aivilable, available_aivilable, ",
        "block_aivilable, sub_account_status, create_time, update_time",
        "from wallet_sub_account",
        "where sub_account_id = #{subAccountId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="sub_account_id", property="subAccountId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="account_id", property="accountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sub_account_type", property="subAccountType", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_aivilable", property="totalAivilable", jdbcType=JdbcType.DECIMAL),
        @Result(column="available_aivilable", property="availableAivilable", jdbcType=JdbcType.DECIMAL),
        @Result(column="block_aivilable", property="blockAivilable", jdbcType=JdbcType.DECIMAL),
        @Result(column="sub_account_status", property="subAccountStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    WalletSubAccount selectByPrimaryKey(String subAccountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WalletSubAccountSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WalletSubAccount record, @Param("example") WalletSubAccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WalletSubAccountSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WalletSubAccount record, @Param("example") WalletSubAccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WalletSubAccountSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WalletSubAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account
     *
     * @mbg.generated
     */
    @Update({
        "update wallet_sub_account",
        "set account_id = #{accountId,jdbcType=VARCHAR},",
          "sub_account_type = #{subAccountType,jdbcType=VARCHAR},",
          "total_aivilable = #{totalAivilable,jdbcType=DECIMAL},",
          "available_aivilable = #{availableAivilable,jdbcType=DECIMAL},",
          "block_aivilable = #{blockAivilable,jdbcType=DECIMAL},",
          "sub_account_status = #{subAccountStatus,jdbcType=TINYINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where sub_account_id = #{subAccountId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WalletSubAccount record);
}