package com.blockchain.commune.mapper;

import com.blockchain.commune.model.WalletDailySummary;
import com.blockchain.commune.model.WalletDailySummaryCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WalletDailySummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_daily_summary
     *
     * @mbg.generated
     */
    @SelectProvider(type=WalletDailySummarySqlProvider.class, method="countByExample")
    long countByExample(WalletDailySummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_daily_summary
     *
     * @mbg.generated
     */
    @DeleteProvider(type=WalletDailySummarySqlProvider.class, method="deleteByExample")
    int deleteByExample(WalletDailySummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_daily_summary
     *
     * @mbg.generated
     */
    @Delete({
        "delete from wallet_daily_summary",
        "where daily_summary_id = #{dailySummaryId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String dailySummaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_daily_summary
     *
     * @mbg.generated
     */
    @Insert({
        "insert into wallet_daily_summary (daily_summary_id, account_id, ",
        "daily_name, trans_amount, ",
        "trans_in_amount, trans_out_amount, ",
        "source_balance, tageet_balance, ",
        "create_time, update_time)",
        "values (#{dailySummaryId,jdbcType=VARCHAR}, #{accountId,jdbcType=VARCHAR}, ",
        "#{dailyName,jdbcType=VARCHAR}, #{transAmount,jdbcType=DECIMAL}, ",
        "#{transInAmount,jdbcType=DECIMAL}, #{transOutAmount,jdbcType=DECIMAL}, ",
        "#{sourceBalance,jdbcType=DECIMAL}, #{tageetBalance,jdbcType=DECIMAL}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(WalletDailySummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_daily_summary
     *
     * @mbg.generated
     */
    @InsertProvider(type=WalletDailySummarySqlProvider.class, method="insertSelective")
    int insertSelective(WalletDailySummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_daily_summary
     *
     * @mbg.generated
     */
    @SelectProvider(type=WalletDailySummarySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="daily_summary_id", property="dailySummaryId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="account_id", property="accountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="daily_name", property="dailyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="trans_amount", property="transAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="trans_in_amount", property="transInAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="trans_out_amount", property="transOutAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="source_balance", property="sourceBalance", jdbcType=JdbcType.DECIMAL),
        @Result(column="tageet_balance", property="tageetBalance", jdbcType=JdbcType.DECIMAL),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<WalletDailySummary> selectByExample(WalletDailySummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_daily_summary
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "daily_summary_id, account_id, daily_name, trans_amount, trans_in_amount, trans_out_amount, ",
        "source_balance, tageet_balance, create_time, update_time",
        "from wallet_daily_summary",
        "where daily_summary_id = #{dailySummaryId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="daily_summary_id", property="dailySummaryId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="account_id", property="accountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="daily_name", property="dailyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="trans_amount", property="transAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="trans_in_amount", property="transInAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="trans_out_amount", property="transOutAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="source_balance", property="sourceBalance", jdbcType=JdbcType.DECIMAL),
        @Result(column="tageet_balance", property="tageetBalance", jdbcType=JdbcType.DECIMAL),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    WalletDailySummary selectByPrimaryKey(String dailySummaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_daily_summary
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WalletDailySummarySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WalletDailySummary record, @Param("example") WalletDailySummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_daily_summary
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WalletDailySummarySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WalletDailySummary record, @Param("example") WalletDailySummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_daily_summary
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WalletDailySummarySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WalletDailySummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_daily_summary
     *
     * @mbg.generated
     */
    @Update({
        "update wallet_daily_summary",
        "set account_id = #{accountId,jdbcType=VARCHAR},",
          "daily_name = #{dailyName,jdbcType=VARCHAR},",
          "trans_amount = #{transAmount,jdbcType=DECIMAL},",
          "trans_in_amount = #{transInAmount,jdbcType=DECIMAL},",
          "trans_out_amount = #{transOutAmount,jdbcType=DECIMAL},",
          "source_balance = #{sourceBalance,jdbcType=DECIMAL},",
          "tageet_balance = #{tageetBalance,jdbcType=DECIMAL},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where daily_summary_id = #{dailySummaryId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WalletDailySummary record);
}