package com.blockchain.commune.mapper;

import com.blockchain.commune.model.WalletSubAccountType;
import com.blockchain.commune.model.WalletSubAccountTypeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WalletSubAccountTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account_type
     *
     * @mbg.generated
     */
    @SelectProvider(type=WalletSubAccountTypeSqlProvider.class, method="countByExample")
    long countByExample(WalletSubAccountTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account_type
     *
     * @mbg.generated
     */
    @DeleteProvider(type=WalletSubAccountTypeSqlProvider.class, method="deleteByExample")
    int deleteByExample(WalletSubAccountTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account_type
     *
     * @mbg.generated
     */
    @Insert({
        "insert into wallet_sub_account_type (sub_account_type, sub_account_type_desc, ",
        "category, create_time)",
        "values (#{subAccountType,jdbcType=VARCHAR}, #{subAccountTypeDesc,jdbcType=VARCHAR}, ",
        "#{category,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(WalletSubAccountType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account_type
     *
     * @mbg.generated
     */
    @InsertProvider(type=WalletSubAccountTypeSqlProvider.class, method="insertSelective")
    int insertSelective(WalletSubAccountType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account_type
     *
     * @mbg.generated
     */
    @SelectProvider(type=WalletSubAccountTypeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="sub_account_type", property="subAccountType", jdbcType=JdbcType.VARCHAR),
        @Result(column="sub_account_type_desc", property="subAccountTypeDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="category", property="category", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<WalletSubAccountType> selectByExample(WalletSubAccountTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account_type
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WalletSubAccountTypeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WalletSubAccountType record, @Param("example") WalletSubAccountTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_sub_account_type
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WalletSubAccountTypeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WalletSubAccountType record, @Param("example") WalletSubAccountTypeCriteria example);
}